@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESStreamOnline
	


## 
## #/components/schemas/StreamOnlineCondition
class Condition extends TwitchData:

	## The broadcaster user ID you want to get stream online notifications for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/StreamOnlineEvent
class Event extends TwitchData:

	## The id of the stream.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## The broadcaster’s user id.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The broadcaster’s user login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The broadcaster’s user display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The stream type. Valid values are: live, playlist, watch_party, premiere, rerun.
	@export var type: String:
		set(val): 
			type = val
			track_data(&"type", val)
	
	## The timestamp at which the stream went online at.
	@export var started_at: String:
		set(val): 
			started_at = val
			track_data(&"started_at", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("type", null) != null:
			result.type = d["type"]
		if d.get("started_at", null) != null:
			result.started_at = d["started_at"]
		return result
	