@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/Outcomes
class_name TwitchESOutcomes
	
## The outcome ID.
@export var id: String:
	set(val): 
		id = val
		track_data(&"id", val)

## The outcome title.
@export var title: String:
	set(val): 
		title = val
		track_data(&"title", val)

## The color for the outcome. Valid values are pink and blue.
@export var color: String:
	set(val): 
		color = val
		track_data(&"color", val)

## The number of users who used Channel Points on this outcome.
@export var users: int:
	set(val): 
		users = val
		track_data(&"users", val)

## The total number of Channel Points used on this outcome.
@export var channel_points: int:
	set(val): 
		channel_points = val
		track_data(&"channel_points", val)

## An array of users who used the most Channel Points on this outcome.
@export var top_predictors: Array[TwitchESTopPredictors]:
	set(val): 
		top_predictors = val
		track_data(&"top_predictors", val)



static func from_json(d: Dictionary) -> TwitchESOutcomes:
	var result: TwitchESOutcomes = TwitchESOutcomes.new()
	if d.get("id", null) != null:
		result.id = d["id"]
	if d.get("title", null) != null:
		result.title = d["title"]
	if d.get("color", null) != null:
		result.color = d["color"]
	if d.get("users", null) != null:
		result.users = d["users"]
	if d.get("channel_points", null) != null:
		result.channel_points = d["channel_points"]
	if d.get("top_predictors", null) != null:
		for value in d["top_predictors"]:
			result.top_predictors.append(TwitchESTopPredictors.from_json(value))
	return result
