@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/ShoutoutCreate
class_name TwitchESShoutoutCreate
	
## An ID that identifies the broadcaster that sent the Shoutout.
@export var broadcaster_user_id: String:
	set(val): 
		broadcaster_user_id = val
		track_data(&"broadcaster_user_id", val)

## The broadcaster’s login name.
@export var broadcaster_user_login: String:
	set(val): 
		broadcaster_user_login = val
		track_data(&"broadcaster_user_login", val)

## The broadcaster’s display name.
@export var broadcaster_user_name: String:
	set(val): 
		broadcaster_user_name = val
		track_data(&"broadcaster_user_name", val)

## An ID that identifies the broadcaster that received the Shoutout.
@export var to_broadcaster_user_id: String:
	set(val): 
		to_broadcaster_user_id = val
		track_data(&"to_broadcaster_user_id", val)

## The broadcaster’s login name.
@export var to_broadcaster_user_login: String:
	set(val): 
		to_broadcaster_user_login = val
		track_data(&"to_broadcaster_user_login", val)

## The broadcaster’s display name.
@export var to_broadcaster_user_name: String:
	set(val): 
		to_broadcaster_user_name = val
		track_data(&"to_broadcaster_user_name", val)

## An ID that identifies the moderator that sent the Shoutout. If the broadcaster sent the Shoutout, this ID is the same as the ID in broadcaster_user_id.
@export var moderator_user_id: String:
	set(val): 
		moderator_user_id = val
		track_data(&"moderator_user_id", val)

## The moderator’s login name.
@export var moderator_user_login: String:
	set(val): 
		moderator_user_login = val
		track_data(&"moderator_user_login", val)

## The moderator’s display name.
@export var moderator_user_name: String:
	set(val): 
		moderator_user_name = val
		track_data(&"moderator_user_name", val)

## The number of users that were watching the broadcaster’s stream at the time of the Shoutout.
@export var viewer_count: int:
	set(val): 
		viewer_count = val
		track_data(&"viewer_count", val)

## The UTC timestamp (in RFC3339 format) of when the moderator sent the Shoutout.
@export var started_at: String:
	set(val): 
		started_at = val
		track_data(&"started_at", val)

## The UTC timestamp (in RFC3339 format) of when the broadcaster may send a Shoutout to a different broadcaster.
@export var cooldown_ends_at: String:
	set(val): 
		cooldown_ends_at = val
		track_data(&"cooldown_ends_at", val)

## The UTC timestamp (in RFC3339 format) of when the broadcaster may send another Shoutout to the broadcaster in to_broadcaster_user_id.
@export var target_cooldown_ends_at: String:
	set(val): 
		target_cooldown_ends_at = val
		track_data(&"target_cooldown_ends_at", val)



static func from_json(d: Dictionary) -> TwitchESShoutoutCreate:
	var result: TwitchESShoutoutCreate = TwitchESShoutoutCreate.new()
	if d.get("broadcaster_user_id", null) != null:
		result.broadcaster_user_id = d["broadcaster_user_id"]
	if d.get("broadcaster_user_login", null) != null:
		result.broadcaster_user_login = d["broadcaster_user_login"]
	if d.get("broadcaster_user_name", null) != null:
		result.broadcaster_user_name = d["broadcaster_user_name"]
	if d.get("to_broadcaster_user_id", null) != null:
		result.to_broadcaster_user_id = d["to_broadcaster_user_id"]
	if d.get("to_broadcaster_user_login", null) != null:
		result.to_broadcaster_user_login = d["to_broadcaster_user_login"]
	if d.get("to_broadcaster_user_name", null) != null:
		result.to_broadcaster_user_name = d["to_broadcaster_user_name"]
	if d.get("moderator_user_id", null) != null:
		result.moderator_user_id = d["moderator_user_id"]
	if d.get("moderator_user_login", null) != null:
		result.moderator_user_login = d["moderator_user_login"]
	if d.get("moderator_user_name", null) != null:
		result.moderator_user_name = d["moderator_user_name"]
	if d.get("viewer_count", null) != null:
		result.viewer_count = d["viewer_count"]
	if d.get("started_at", null) != null:
		result.started_at = d["started_at"]
	if d.get("cooldown_ends_at", null) != null:
		result.cooldown_ends_at = d["cooldown_ends_at"]
	if d.get("target_cooldown_ends_at", null) != null:
		result.target_cooldown_ends_at = d["target_cooldown_ends_at"]
	return result
