@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESCharityDonation
	


## 
## #/components/schemas/CharityDonationEvent
class Event extends TwitchData:

	## An ID that identifies the donation. The ID is unique across campaigns.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## An ID that identifies the charity campaign.
	@export var campaign_id: String:
		set(val): 
			campaign_id = val
			track_data(&"campaign_id", val)
	
	## An ID that identifies the broadcaster that’s running the campaign.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The broadcaster’s login name.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The broadcaster’s display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## An ID that identifies the user that donated to the campaign.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The user’s login name.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user’s display name.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The charity’s name.
	@export var charity_name: String:
		set(val): 
			charity_name = val
			track_data(&"charity_name", val)
	
	## A description of the charity.
	@export var charity_description: String:
		set(val): 
			charity_description = val
			track_data(&"charity_description", val)
	
	## A URL to an image of the charity’s logo. The image’s type is PNG and its size is 100px X 100px.
	@export var charity_logo: String:
		set(val): 
			charity_logo = val
			track_data(&"charity_logo", val)
	
	## A URL to the charity’s website.
	@export var charity_website: String:
		set(val): 
			charity_website = val
			track_data(&"charity_website", val)
	
	## An object that contains the amount of money that the user donated.
	@export var amount: Amount:
		set(val): 
			amount = val
			track_data(&"amount", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("campaign_id", null) != null:
			result.campaign_id = d["campaign_id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("charity_name", null) != null:
			result.charity_name = d["charity_name"]
		if d.get("charity_description", null) != null:
			result.charity_description = d["charity_description"]
		if d.get("charity_logo", null) != null:
			result.charity_logo = d["charity_logo"]
		if d.get("charity_website", null) != null:
			result.charity_website = d["charity_website"]
		if d.get("amount", null) != null:
			result.amount = Amount.from_json(d["amount"])
		return result
	


## An object that contains the amount of money that the user donated.
## #/components/schemas/CharityDonationEvent/Amount
class Amount extends TwitchData:

	## The monetary amount. The amount is specified in the currency’s minor unit. For example, the minor units for USD is cents, so if the amount is $5.50 USD, value is set to 550.
	@export var value: int:
		set(val): 
			value = val
			track_data(&"value", val)
	
	## The number of decimal places used by the currency. For example, USD uses two decimal places. Use this number to translate value from minor units to major units by using the formula:value / 10^decimal_places
	@export var decimal_places: int:
		set(val): 
			decimal_places = val
			track_data(&"decimal_places", val)
	
	## The ISO-4217 three-letter currency code that identifies the type of currency in value.
	@export var currency: String:
		set(val): 
			currency = val
			track_data(&"currency", val)
	
	
	
	static func from_json(d: Dictionary) -> Amount:
		var result: Amount = Amount.new()
		if d.get("value", null) != null:
			result.value = d["value"]
		if d.get("decimal_places", null) != null:
			result.decimal_places = d["decimal_places"]
		if d.get("currency", null) != null:
			result.currency = d["currency"]
		return result
	