@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/MaxPerStream
class_name TwitchESMaxPerStream
	
## Is the setting enabled.
@export var is_enabled: bool:
	set(val): 
		is_enabled = val
		track_data(&"is_enabled", val)

## The max per stream limit.
@export var value: int:
	set(val): 
		value = val
		track_data(&"value", val)



static func from_json(d: Dictionary) -> TwitchESMaxPerStream:
	var result: TwitchESMaxPerStream = TwitchESMaxPerStream.new()
	if d.get("is_enabled", null) != null:
		result.is_enabled = d["is_enabled"]
	if d.get("value", null) != null:
		result.value = d["value"]
	return result
