@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelSharedChatSessionEnd
	


## 
## #/components/schemas/ChannelSharedChatSessionEndCondition
class Condition extends TwitchData:

	## The User ID of the channel to receive shared chat session end events for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelSharedChatSessionEndEvent
class Event extends TwitchData:

	## The unique identifier for the shared chat session.
	@export var session_id: String:
		set(val): 
			session_id = val
			track_data(&"session_id", val)
	
	## The User ID of the channel in the subscription condition which is no longer active in the shared chat session.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The display name of the channel in the subscription condition which is no longer active in the shared chat session.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The user login of the channel in the subscription condition which is no longer active in the shared chat session.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The User ID of the host channel.
	@export var host_broadcaster_user_id: String:
		set(val): 
			host_broadcaster_user_id = val
			track_data(&"host_broadcaster_user_id", val)
	
	## The display name of the host channel.
	@export var host_broadcaster_user_name: String:
		set(val): 
			host_broadcaster_user_name = val
			track_data(&"host_broadcaster_user_name", val)
	
	## The user login of the host channel.
	@export var host_broadcaster_user_login: String:
		set(val): 
			host_broadcaster_user_login = val
			track_data(&"host_broadcaster_user_login", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("session_id", null) != null:
			result.session_id = d["session_id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("host_broadcaster_user_id", null) != null:
			result.host_broadcaster_user_id = d["host_broadcaster_user_id"]
		if d.get("host_broadcaster_user_name", null) != null:
			result.host_broadcaster_user_name = d["host_broadcaster_user_name"]
		if d.get("host_broadcaster_user_login", null) != null:
			result.host_broadcaster_user_login = d["host_broadcaster_user_login"]
		return result
	