@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESAutomodTermsUpdate
	


## 
## #/components/schemas/AutomodTermsUpdateCondition
class Condition extends TwitchData:

	## User ID of the broadcaster (channel). Maximum:1.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## User ID of the moderator creating the subscription. Maximum:1
	@export var moderator_user_id: String:
		set(val): 
			moderator_user_id = val
			track_data(&"moderator_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("moderator_user_id", null) != null:
			result.moderator_user_id = d["moderator_user_id"]
		return result
	


## 
## #/components/schemas/AutomodTermsUpdateEvent
class Event extends TwitchData:

	## The ID of the broadcaster specified in the request.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The login of the broadcaster specified in the request.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The user name of the broadcaster specified in the request.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The ID of the moderator who changed the channel settings.
	@export var moderator_user_id: String:
		set(val): 
			moderator_user_id = val
			track_data(&"moderator_user_id", val)
	
	## The moderator’s login.
	@export var moderator_user_login: String:
		set(val): 
			moderator_user_login = val
			track_data(&"moderator_user_login", val)
	
	## The moderator’s user name.
	@export var moderator_user_name: String:
		set(val): 
			moderator_user_name = val
			track_data(&"moderator_user_name", val)
	
	## The status change applied to the terms. Possible options are: add_permittedremove_permittedadd_blockedremove_blocked
	@export var action: String:
		set(val): 
			action = val
			track_data(&"action", val)
	
	## Indicates whether this term was added due to an Automod message approve/deny action.
	@export var from_automod: bool:
		set(val): 
			from_automod = val
			track_data(&"from_automod", val)
	
	## The list of terms that had a status change.
	@export var terms: Array[String]:
		set(val): 
			terms = val
			track_data(&"terms", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("moderator_user_id", null) != null:
			result.moderator_user_id = d["moderator_user_id"]
		if d.get("moderator_user_login", null) != null:
			result.moderator_user_login = d["moderator_user_login"]
		if d.get("moderator_user_name", null) != null:
			result.moderator_user_name = d["moderator_user_name"]
		if d.get("action", null) != null:
			result.action = d["action"]
		if d.get("from_automod", null) != null:
			result.from_automod = d["from_automod"]
		if d.get("terms", null) != null:
			for value in d["terms"]:
				result.terms.append(value)
		return result
	