@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/Message
class_name TwitchESMessage
	
## The text of the resubscription chat message.
@export var text: String:
	set(val): 
		text = val
		track_data(&"text", val)

## An array that includes the emote ID and start and end positions for where the emote appears in the text.
@export var emotes: Array[TwitchESEmotes]:
	set(val): 
		emotes = val
		track_data(&"emotes", val)



static func from_json(d: Dictionary) -> TwitchESMessage:
	var result: TwitchESMessage = TwitchESMessage.new()
	if d.get("text", null) != null:
		result.text = d["text"]
	if d.get("emotes", null) != null:
		for value in d["emotes"]:
			result.emotes.append(TwitchESEmotes.from_json(value))
	return result
