@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/ShoutoutReceived
class_name TwitchESShoutoutReceived
	
## An ID that identifies the broadcaster that received the Shoutout.
@export var broadcaster_user_id: String:
	set(val): 
		broadcaster_user_id = val
		track_data(&"broadcaster_user_id", val)

## The broadcaster’s login name.
@export var broadcaster_user_login: String:
	set(val): 
		broadcaster_user_login = val
		track_data(&"broadcaster_user_login", val)

## The broadcaster’s display name.
@export var broadcaster_user_name: String:
	set(val): 
		broadcaster_user_name = val
		track_data(&"broadcaster_user_name", val)

## An ID that identifies the broadcaster that sent the Shoutout.
@export var from_broadcaster_user_id: String:
	set(val): 
		from_broadcaster_user_id = val
		track_data(&"from_broadcaster_user_id", val)

## The broadcaster’s login name.
@export var from_broadcaster_user_login: String:
	set(val): 
		from_broadcaster_user_login = val
		track_data(&"from_broadcaster_user_login", val)

## The broadcaster’s display name.
@export var from_broadcaster_user_name: String:
	set(val): 
		from_broadcaster_user_name = val
		track_data(&"from_broadcaster_user_name", val)

## The number of users that were watching the from-broadcaster’s stream at the time of the Shoutout.
@export var viewer_count: int:
	set(val): 
		viewer_count = val
		track_data(&"viewer_count", val)

## The UTC timestamp (in RFC3339 format) of when the moderator sent the Shoutout.
@export var started_at: String:
	set(val): 
		started_at = val
		track_data(&"started_at", val)



static func from_json(d: Dictionary) -> TwitchESShoutoutReceived:
	var result: TwitchESShoutoutReceived = TwitchESShoutoutReceived.new()
	if d.get("broadcaster_user_id", null) != null:
		result.broadcaster_user_id = d["broadcaster_user_id"]
	if d.get("broadcaster_user_login", null) != null:
		result.broadcaster_user_login = d["broadcaster_user_login"]
	if d.get("broadcaster_user_name", null) != null:
		result.broadcaster_user_name = d["broadcaster_user_name"]
	if d.get("from_broadcaster_user_id", null) != null:
		result.from_broadcaster_user_id = d["from_broadcaster_user_id"]
	if d.get("from_broadcaster_user_login", null) != null:
		result.from_broadcaster_user_login = d["from_broadcaster_user_login"]
	if d.get("from_broadcaster_user_name", null) != null:
		result.from_broadcaster_user_name = d["from_broadcaster_user_name"]
	if d.get("viewer_count", null) != null:
		result.viewer_count = d["viewer_count"]
	if d.get("started_at", null) != null:
		result.started_at = d["started_at"]
	return result
