@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelAdBreakBegin
	


## 
## #/components/schemas/ChannelAdBreakBeginCondition
class Condition extends TwitchData:

	## The ID of the broadcaster that you want to get Channel Ad Break begin notifications for. Maximum: 1
	@export var broadcaster_id: String:
		set(val): 
			broadcaster_id = val
			track_data(&"broadcaster_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_id", null) != null:
			result.broadcaster_id = d["broadcaster_id"]
		return result
	


## 
## #/components/schemas/ChannelAdBreakBeginEvent
class Event extends TwitchData:

	## Length in seconds of the mid-roll ad break requested
	@export var duration_seconds: int:
		set(val): 
			duration_seconds = val
			track_data(&"duration_seconds", val)
	
	## The UTC timestamp of when the ad break began, in RFC3339 format. Note that there is potential delay between this event, when the streamer requested the ad break, and when the viewers will see ads.
	@export var started_at: String:
		set(val): 
			started_at = val
			track_data(&"started_at", val)
	
	## Indicates if the ad was automatically scheduled via Ads Manager
	@export var is_automatic: bool:
		set(val): 
			is_automatic = val
			track_data(&"is_automatic", val)
	
	## The broadcaster’s user ID for the channel the ad was run on.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The broadcaster’s user login for the channel the ad was run on.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The broadcaster’s user display name for the channel the ad was run on.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The ID of the user that requested the ad. For automatic ads, this will be the ID of the broadcaster.
	@export var requester_user_id: String:
		set(val): 
			requester_user_id = val
			track_data(&"requester_user_id", val)
	
	## The login of the user that requested the ad.
	@export var requester_user_login: String:
		set(val): 
			requester_user_login = val
			track_data(&"requester_user_login", val)
	
	## The display name of the user that requested the ad.
	@export var requester_user_name: String:
		set(val): 
			requester_user_name = val
			track_data(&"requester_user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("duration_seconds", null) != null:
			result.duration_seconds = d["duration_seconds"]
		if d.get("started_at", null) != null:
			result.started_at = d["started_at"]
		if d.get("is_automatic", null) != null:
			result.is_automatic = d["is_automatic"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("requester_user_id", null) != null:
			result.requester_user_id = d["requester_user_id"]
		if d.get("requester_user_login", null) != null:
			result.requester_user_login = d["requester_user_login"]
		if d.get("requester_user_name", null) != null:
			result.requester_user_name = d["requester_user_name"]
		return result
	