@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/ChannelPointsVoting
class_name TwitchESChannelPointsVoting
	
## Indicates if Channel Points can be used for voting.
@export var is_enabled: bool:
	set(val): 
		is_enabled = val
		track_data(&"is_enabled", val)

## Number of Channel Points required to vote once with Channel Points.
@export var amount_per_vote: int:
	set(val): 
		amount_per_vote = val
		track_data(&"amount_per_vote", val)



static func from_json(d: Dictionary) -> TwitchESChannelPointsVoting:
	var result: TwitchESChannelPointsVoting = TwitchESChannelPointsVoting.new()
	if d.get("is_enabled", null) != null:
		result.is_enabled = d["is_enabled"]
	if d.get("amount_per_vote", null) != null:
		result.amount_per_vote = d["amount_per_vote"]
	return result
