@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelPointsCustomRewardAdd
	


## 
## #/components/schemas/ChannelPointsCustomRewardAddCondition
class Condition extends TwitchData:

	## The broadcaster user ID for the channel you want to receive channel points custom reward add notifications for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelPointsCustomRewardAddEvent
class Event extends TwitchData:

	## The reward identifier.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## The requested broadcaster ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The requested broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The requested broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## Is the reward currently enabled. If false, the reward won’t show up to viewers.
	@export var is_enabled: bool:
		set(val): 
			is_enabled = val
			track_data(&"is_enabled", val)
	
	## Is the reward currently paused. If true, viewers can’t redeem.
	@export var is_paused: bool:
		set(val): 
			is_paused = val
			track_data(&"is_paused", val)
	
	## Is the reward currently in stock. If false, viewers can’t redeem.
	@export var is_in_stock: bool:
		set(val): 
			is_in_stock = val
			track_data(&"is_in_stock", val)
	
	## The reward title.
	@export var title: String:
		set(val): 
			title = val
			track_data(&"title", val)
	
	## The reward cost.
	@export var cost: int:
		set(val): 
			cost = val
			track_data(&"cost", val)
	
	## The reward description.
	@export var prompt: String:
		set(val): 
			prompt = val
			track_data(&"prompt", val)
	
	## Does the viewer need to enter information when redeeming the reward.
	@export var is_user_input_required: bool:
		set(val): 
			is_user_input_required = val
			track_data(&"is_user_input_required", val)
	
	## Should redemptions be set to fulfilled status immediately when redeemed and skip the request queue instead of the normal unfulfilled status.
	@export var should_redemptions_skip_request_queue: bool:
		set(val): 
			should_redemptions_skip_request_queue = val
			track_data(&"should_redemptions_skip_request_queue", val)
	
	## Whether a maximum per stream is enabled and what the maximum is.
	@export var max_per_stream: TwitchESMaxPerStream:
		set(val): 
			max_per_stream = val
			track_data(&"max_per_stream", val)
	
	## Whether a maximum per user per stream is enabled and what the maximum is.
	@export var max_per_user_per_stream: TwitchESMaxPerUserPerStream:
		set(val): 
			max_per_user_per_stream = val
			track_data(&"max_per_user_per_stream", val)
	
	## Custom background color for the reward. Format: Hex with # prefix. Example: #FA1ED2.
	@export var background_color: String:
		set(val): 
			background_color = val
			track_data(&"background_color", val)
	
	## Set of custom images of 1x, 2x and 4x sizes for the reward. Can be null if no images have been uploaded.
	@export var image: TwitchESTwitchImage:
		set(val): 
			image = val
			track_data(&"image", val)
	
	## Set of default images of 1x, 2x and 4x sizes for the reward.
	@export var default_image: TwitchESTwitchImage:
		set(val): 
			default_image = val
			track_data(&"default_image", val)
	
	## Whether a cooldown is enabled and what the cooldown is in seconds.
	@export var global_cooldown: TwitchESGlobalCooldown:
		set(val): 
			global_cooldown = val
			track_data(&"global_cooldown", val)
	
	## Timestamp of the cooldown expiration. null if the reward isn’t on cooldown.
	@export var cooldown_expires_at: String:
		set(val): 
			cooldown_expires_at = val
			track_data(&"cooldown_expires_at", val)
	
	## The number of redemptions redeemed during the current live stream. Counts against the max_per_stream limit. null if the broadcasters stream isn’t live or max_per_stream isn’t enabled.
	@export var redemptions_redeemed_current_stream: int:
		set(val): 
			redemptions_redeemed_current_stream = val
			track_data(&"redemptions_redeemed_current_stream", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("is_enabled", null) != null:
			result.is_enabled = d["is_enabled"]
		if d.get("is_paused", null) != null:
			result.is_paused = d["is_paused"]
		if d.get("is_in_stock", null) != null:
			result.is_in_stock = d["is_in_stock"]
		if d.get("title", null) != null:
			result.title = d["title"]
		if d.get("cost", null) != null:
			result.cost = d["cost"]
		if d.get("prompt", null) != null:
			result.prompt = d["prompt"]
		if d.get("is_user_input_required", null) != null:
			result.is_user_input_required = d["is_user_input_required"]
		if d.get("should_redemptions_skip_request_queue", null) != null:
			result.should_redemptions_skip_request_queue = d["should_redemptions_skip_request_queue"]
		if d.get("max_per_stream", null) != null:
			result.max_per_stream = TwitchESMaxPerStream.from_json(d["max_per_stream"])
		if d.get("max_per_user_per_stream", null) != null:
			result.max_per_user_per_stream = TwitchESMaxPerUserPerStream.from_json(d["max_per_user_per_stream"])
		if d.get("background_color", null) != null:
			result.background_color = d["background_color"]
		if d.get("image", null) != null:
			result.image = TwitchESTwitchImage.from_json(d["image"])
		if d.get("default_image", null) != null:
			result.default_image = TwitchESTwitchImage.from_json(d["default_image"])
		if d.get("global_cooldown", null) != null:
			result.global_cooldown = TwitchESGlobalCooldown.from_json(d["global_cooldown"])
		if d.get("cooldown_expires_at", null) != null:
			result.cooldown_expires_at = d["cooldown_expires_at"]
		if d.get("redemptions_redeemed_current_stream", null) != null:
			result.redemptions_redeemed_current_stream = d["redemptions_redeemed_current_stream"]
		return result
	