@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/BitsVoting
class_name TwitchESBitsVoting
	
## Not used; will be set to false.
@export var is_enabled: bool:
	set(val): 
		is_enabled = val
		track_data(&"is_enabled", val)

## Not used; will be set to 0.
@export var amount_per_vote: int:
	set(val): 
		amount_per_vote = val
		track_data(&"amount_per_vote", val)



static func from_json(d: Dictionary) -> TwitchESBitsVoting:
	var result: TwitchESBitsVoting = TwitchESBitsVoting.new()
	if d.get("is_enabled", null) != null:
		result.is_enabled = d["is_enabled"]
	if d.get("amount_per_vote", null) != null:
		result.amount_per_vote = d["amount_per_vote"]
	return result
