@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelUpdate
	


## 
## #/components/schemas/ChannelUpdateCondition
class Condition extends TwitchData:

	## The broadcaster user ID for the channel you want to get updates for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelUpdateEvent
class Event extends TwitchData:

	## The broadcaster’s user ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The broadcaster’s user login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The broadcaster’s user display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The channel’s stream title.
	@export var title: String:
		set(val): 
			title = val
			track_data(&"title", val)
	
	## The channel’s broadcast language.
	@export var language: String:
		set(val): 
			language = val
			track_data(&"language", val)
	
	## The channel’s category ID.
	@export var category_id: String:
		set(val): 
			category_id = val
			track_data(&"category_id", val)
	
	## The category name.
	@export var category_name: String:
		set(val): 
			category_name = val
			track_data(&"category_name", val)
	
	## Array of content classification label IDs currently applied on the Channel. To retrieve a list of all possible IDs, use the Get Content Classification Labels API endpoint.
	@export var content_classification_labels: Array[String]:
		set(val): 
			content_classification_labels = val
			track_data(&"content_classification_labels", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("title", null) != null:
			result.title = d["title"]
		if d.get("language", null) != null:
			result.language = d["language"]
		if d.get("category_id", null) != null:
			result.category_id = d["category_id"]
		if d.get("category_name", null) != null:
			result.category_name = d["category_name"]
		if d.get("content_classification_labels", null) != null:
			for value in d["content_classification_labels"]:
				result.content_classification_labels.append(value)
		return result
	