@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelGuestStarSessionEnd
	


## 
## #/components/schemas/ChannelGuestStarSessionEndCondition
class Condition extends TwitchData:

	## The broadcaster user ID of the channel hosting the Guest Star Session
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The user ID of the moderator or broadcaster of the specified channel.
	@export var moderator_user_id: String:
		set(val): 
			moderator_user_id = val
			track_data(&"moderator_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("moderator_user_id", null) != null:
			result.moderator_user_id = d["moderator_user_id"]
		return result
	


## 
## #/components/schemas/ChannelGuestStarSessionEndEvent
class Event extends TwitchData:

	## The non-host broadcaster user ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The non-host broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The non-host broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## ID representing the unique session that was started.
	@export var session_id: String:
		set(val): 
			session_id = val
			track_data(&"session_id", val)
	
	## RFC3339 timestamp indicating the time the session began.
	@export var started_at: String:
		set(val): 
			started_at = val
			track_data(&"started_at", val)
	
	## RFC3339 timestamp indicating the time the session ended.
	@export var ended_at: String:
		set(val): 
			ended_at = val
			track_data(&"ended_at", val)
	
	## User ID of the host channel.
	@export var host_user_id: String:
		set(val): 
			host_user_id = val
			track_data(&"host_user_id", val)
	
	## The host display name.
	@export var host_user_name: String:
		set(val): 
			host_user_name = val
			track_data(&"host_user_name", val)
	
	## The host login.
	@export var host_user_login: String:
		set(val): 
			host_user_login = val
			track_data(&"host_user_login", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("session_id", null) != null:
			result.session_id = d["session_id"]
		if d.get("started_at", null) != null:
			result.started_at = d["started_at"]
		if d.get("ended_at", null) != null:
			result.ended_at = d["ended_at"]
		if d.get("host_user_id", null) != null:
			result.host_user_id = d["host_user_id"]
		if d.get("host_user_name", null) != null:
			result.host_user_name = d["host_user_name"]
		if d.get("host_user_login", null) != null:
			result.host_user_login = d["host_user_login"]
		return result
	