@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelChatSettingsUpdate
	


## 
## #/components/schemas/ChannelChatSettingsUpdateCondition
class Condition extends TwitchData:

	## User ID of the channel to receive chat settings update events for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The user ID to read chat as.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		return result
	


## 
## #/components/schemas/ChannelChatSettingsUpdateEvent
class Event extends TwitchData:

	## The ID of the broadcaster specified in the request.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The login of the broadcaster specified in the request.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The user name of the broadcaster specified in the request.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## A Boolean value that determines whether chat messages must contain only emotes. True if only messages that are 100% emotes are allowed; otherwise false.
	@export var emote_mode: bool:
		set(val): 
			emote_mode = val
			track_data(&"emote_mode", val)
	
	## A Boolean value that determines whether the broadcaster restricts the chat room to followers only, based on how long they’ve followed.True if the broadcaster restricts the chat room to followers only; otherwise false.See follower_mode_duration_minutes for how long the followers must have followed the broadcaster to participate in the chat room.
	@export var follower_mode: bool:
		set(val): 
			follower_mode = val
			track_data(&"follower_mode", val)
	
	## The length of time, in minutes, that the followers must have followed the broadcaster to participate in the chat room. See follower_mode.Null if follower_mode is false.
	@export var follower_mode_duration_minutes: int:
		set(val): 
			follower_mode_duration_minutes = val
			track_data(&"follower_mode_duration_minutes", val)
	
	## A Boolean value that determines whether the broadcaster limits how often users in the chat room are allowed to send messages.Is true, if the broadcaster applies a delay; otherwise, false.See slow_mode_wait_time_seconds for the delay.
	@export var slow_mode: bool:
		set(val): 
			slow_mode = val
			track_data(&"slow_mode", val)
	
	## The amount of time, in seconds, that users need to wait between sending messages. See slow_mode.Null if slow_mode is false.
	@export var slow_mode_wait_time_seconds: int:
		set(val): 
			slow_mode_wait_time_seconds = val
			track_data(&"slow_mode_wait_time_seconds", val)
	
	## A Boolean value that determines whether only users that subscribe to the broadcaster’s channel can talk in the chat room.True if the broadcaster restricts the chat room to subscribers only; otherwise false.
	@export var subscriber_mode: bool:
		set(val): 
			subscriber_mode = val
			track_data(&"subscriber_mode", val)
	
	## A Boolean value that determines whether the broadcaster requires users to post only unique messages in the chat room.True if the broadcaster requires unique messages only; otherwise false.
	@export var unique_chat_mode: bool:
		set(val): 
			unique_chat_mode = val
			track_data(&"unique_chat_mode", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("emote_mode", null) != null:
			result.emote_mode = d["emote_mode"]
		if d.get("follower_mode", null) != null:
			result.follower_mode = d["follower_mode"]
		if d.get("follower_mode_duration_minutes", null) != null:
			result.follower_mode_duration_minutes = d["follower_mode_duration_minutes"]
		if d.get("slow_mode", null) != null:
			result.slow_mode = d["slow_mode"]
		if d.get("slow_mode_wait_time_seconds", null) != null:
			result.slow_mode_wait_time_seconds = d["slow_mode_wait_time_seconds"]
		if d.get("subscriber_mode", null) != null:
			result.subscriber_mode = d["subscriber_mode"]
		if d.get("unique_chat_mode", null) != null:
			result.unique_chat_mode = d["unique_chat_mode"]
		return result
	