@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelCheer
	


## 
## #/components/schemas/ChannelCheerCondition
class Condition extends TwitchData:

	## The broadcaster user ID for the channel you want to get cheer notifications for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelCheerEvent
class Event extends TwitchData:

	## Whether the user cheered anonymously or not.
	@export var is_anonymous: bool:
		set(val): 
			is_anonymous = val
			track_data(&"is_anonymous", val)
	
	## The user ID for the user who cheered on the specified channel. This is null if is_anonymous is true.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The user login for the user who cheered on the specified channel. This is null if is_anonymous is true.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user display name for the user who cheered on the specified channel. This is null if is_anonymous is true.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The requested broadcaster ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The requested broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The requested broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The message sent with the cheer.
	@export var message: String:
		set(val): 
			message = val
			track_data(&"message", val)
	
	## The number of Bits cheered.
	@export var bits: int:
		set(val): 
			bits = val
			track_data(&"bits", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("is_anonymous", null) != null:
			result.is_anonymous = d["is_anonymous"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("message", null) != null:
			result.message = d["message"]
		if d.get("bits", null) != null:
			result.bits = d["bits"]
		return result
	