@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelChatMessage
	


## 
## #/components/schemas/ChannelChatMessageCondition
class Condition extends TwitchData:

	## The User ID of the channel to receive chat message events for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The User ID to read chat as.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		return result
	


## 
## #/components/schemas/ChannelChatMessageEvent
class Event extends TwitchData:

	## The broadcaster user ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The user ID of the user that sent the message.
	@export var chatter_user_id: String:
		set(val): 
			chatter_user_id = val
			track_data(&"chatter_user_id", val)
	
	## The user name of the user that sent the message.
	@export var chatter_user_name: String:
		set(val): 
			chatter_user_name = val
			track_data(&"chatter_user_name", val)
	
	## The user login of the user that sent the message.
	@export var chatter_user_login: String:
		set(val): 
			chatter_user_login = val
			track_data(&"chatter_user_login", val)
	
	## A UUID that identifies the message.
	@export var message_id: String:
		set(val): 
			message_id = val
			track_data(&"message_id", val)
	
	## The structured chat message.
	@export var message: Message:
		set(val): 
			message = val
			track_data(&"message", val)
	
	## The type of message. Possible values: <ul><li>text</li><li>channel_points_highlighted</li><li>channel_points_sub_only</li><li>user_intro</li><li>power_ups_message_effect</li><li>power_ups_gigantified_emote</li></ul>
	@export var message_type: String:
		set(val): 
			message_type = val
			track_data(&"message_type", val)
	
	## List of chat badges.
	@export var badges: Array[Badges]:
		set(val): 
			badges = val
			track_data(&"badges", val)
	
	## Optional. Metadata if this message is a cheer.
	@export var cheer: Cheer:
		set(val): 
			cheer = val
			track_data(&"cheer", val)
	
	## The color of the user’s name in the chat room. This is a hexadecimal RGB color code in the form, #&lt;RGB&gt;. This tag may be empty if it is never set.
	@export var color: String:
		set(val): 
			color = val
			track_data(&"color", val)
	
	## Optional. Metadata if this message is a reply.
	@export var reply: Reply:
		set(val): 
			reply = val
			track_data(&"reply", val)
	
	## Optional. The ID of a channel points custom reward that was redeemed.
	@export var channel_points_custom_reward_id: String:
		set(val): 
			channel_points_custom_reward_id = val
			track_data(&"channel_points_custom_reward_id", val)
	
	## Optional. The broadcaster user ID of the channel the message was sent from. Is null when the message happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_broadcaster_user_id: String:
		set(val): 
			source_broadcaster_user_id = val
			track_data(&"source_broadcaster_user_id", val)
	
	## Optional. The user name of the broadcaster of the channel the message was sent from. Is null when the message happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_broadcaster_user_name: String:
		set(val): 
			source_broadcaster_user_name = val
			track_data(&"source_broadcaster_user_name", val)
	
	## Optional. The login of the broadcaster of the channel the message was sent from. Is null when the message happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_broadcaster_user_login: String:
		set(val): 
			source_broadcaster_user_login = val
			track_data(&"source_broadcaster_user_login", val)
	
	## Optional. The UUID that identifies the source message from the channel the message was sent from. Is null when the message happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_message_id: String:
		set(val): 
			source_message_id = val
			track_data(&"source_message_id", val)
	
	## Optional. The list of chat badges for the chatter in the channel the message was sent from. Is null when the message happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_badges: SourceBadges:
		set(val): 
			source_badges = val
			track_data(&"source_badges", val)
	
	## Optional. Determines if a message delivered during a shared chat session is only sent to the source channel. Has no effect if the message is not sent during a shared chat session.
	@export var is_source_only: bool:
		set(val): 
			is_source_only = val
			track_data(&"is_source_only", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("chatter_user_id", null) != null:
			result.chatter_user_id = d["chatter_user_id"]
		if d.get("chatter_user_name", null) != null:
			result.chatter_user_name = d["chatter_user_name"]
		if d.get("chatter_user_login", null) != null:
			result.chatter_user_login = d["chatter_user_login"]
		if d.get("message_id", null) != null:
			result.message_id = d["message_id"]
		if d.get("message", null) != null:
			result.message = Message.from_json(d["message"])
		if d.get("message_type", null) != null:
			result.message_type = d["message_type"]
		if d.get("badges", null) != null:
			for value in d["badges"]:
				result.badges.append(Badges.from_json(value))
		if d.get("cheer", null) != null:
			result.cheer = Cheer.from_json(d["cheer"])
		if d.get("color", null) != null:
			result.color = d["color"]
		if d.get("reply", null) != null:
			result.reply = Reply.from_json(d["reply"])
		if d.get("channel_points_custom_reward_id", null) != null:
			result.channel_points_custom_reward_id = d["channel_points_custom_reward_id"]
		if d.get("source_broadcaster_user_id", null) != null:
			result.source_broadcaster_user_id = d["source_broadcaster_user_id"]
		if d.get("source_broadcaster_user_name", null) != null:
			result.source_broadcaster_user_name = d["source_broadcaster_user_name"]
		if d.get("source_broadcaster_user_login", null) != null:
			result.source_broadcaster_user_login = d["source_broadcaster_user_login"]
		if d.get("source_message_id", null) != null:
			result.source_message_id = d["source_message_id"]
		if d.get("source_badges", null) != null:
			result.source_badges = SourceBadges.from_json(d["source_badges"])
		if d.get("is_source_only", null) != null:
			result.is_source_only = d["is_source_only"]
		return result
	


## The structured chat message.
## #/components/schemas/ChannelChatMessageEvent/Message
class Message extends TwitchData:

	## The chat message in plain text.
	@export var text: String:
		set(val): 
			text = val
			track_data(&"text", val)
	
	## Ordered list of chat message fragments.
	@export var fragments: Array[Fragments]:
		set(val): 
			fragments = val
			track_data(&"fragments", val)
	
	
	
	static func from_json(d: Dictionary) -> Message:
		var result: Message = Message.new()
		if d.get("text", null) != null:
			result.text = d["text"]
		if d.get("fragments", null) != null:
			for value in d["fragments"]:
				result.fragments.append(Fragments.from_json(value))
		return result
	


## Ordered list of chat message fragments.
## #/components/schemas/ChannelChatMessageEvent/Message/Fragments
class Fragments extends TwitchData:

	## The type of message fragment. Possible values: textcheermoteemotemention
	@export var type: String:
		set(val): 
			type = val
			track_data(&"type", val)
	
	## Message text in fragment.
	@export var text: String:
		set(val): 
			text = val
			track_data(&"text", val)
	
	## Optional. Metadata pertaining to the cheermote.
	@export var cheermote: Cheermote:
		set(val): 
			cheermote = val
			track_data(&"cheermote", val)
	
	## Optional. Metadata pertaining to the emote.
	@export var emote: Emote:
		set(val): 
			emote = val
			track_data(&"emote", val)
	
	## Optional. Metadata pertaining to the mention.
	@export var mention: Mention:
		set(val): 
			mention = val
			track_data(&"mention", val)
	
	
	
	static func from_json(d: Dictionary) -> Fragments:
		var result: Fragments = Fragments.new()
		if d.get("type", null) != null:
			result.type = d["type"]
		if d.get("text", null) != null:
			result.text = d["text"]
		if d.get("cheermote", null) != null:
			result.cheermote = Cheermote.from_json(d["cheermote"])
		if d.get("emote", null) != null:
			result.emote = Emote.from_json(d["emote"])
		if d.get("mention", null) != null:
			result.mention = Mention.from_json(d["mention"])
		return result
	


## Optional. Metadata pertaining to the cheermote.
## #/components/schemas/ChannelChatMessageEvent/Message/Fragments/Cheermote
class Cheermote extends TwitchData:

	## The name portion of the Cheermote string that you use in chat to cheer Bits. The full Cheermote string is the concatenation of {prefix} + {number of Bits}. For example, if the prefix is “Cheer” and you want to cheer 100 Bits, the full Cheermote string is Cheer100. When the Cheermote string is entered in chat, Twitch converts it to the image associated with the Bits tier that was cheered.
	@export var prefix: String:
		set(val): 
			prefix = val
			track_data(&"prefix", val)
	
	## The amount of Bits cheered.
	@export var bits: int:
		set(val): 
			bits = val
			track_data(&"bits", val)
	
	## The tier level of the cheermote.
	@export var tier: int:
		set(val): 
			tier = val
			track_data(&"tier", val)
	
	
	
	static func from_json(d: Dictionary) -> Cheermote:
		var result: Cheermote = Cheermote.new()
		if d.get("prefix", null) != null:
			result.prefix = d["prefix"]
		if d.get("bits", null) != null:
			result.bits = d["bits"]
		if d.get("tier", null) != null:
			result.tier = d["tier"]
		return result
	


## Optional. Metadata pertaining to the emote.
## #/components/schemas/ChannelChatMessageEvent/Message/Fragments/Emote
class Emote extends TwitchData:

	## An ID that uniquely identifies this emote.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## An ID that identifies the emote set that the emote belongs to.
	@export var emote_set_id: String:
		set(val): 
			emote_set_id = val
			track_data(&"emote_set_id", val)
	
	## The ID of the broadcaster who owns the emote.
	@export var owner_id: String:
		set(val): 
			owner_id = val
			track_data(&"owner_id", val)
	
	## The formats that the emote is available in. For example, if the emote is available only as a static PNG, the array contains only static. But if the emote is available as a static PNG and an animated GIF, the array contains static and animated. The possible formats are: animated - An animated GIF is available for this emote.static - A static PNG file is available for this emote.
	@export var format: Array[String]:
		set(val): 
			format = val
			track_data(&"format", val)
	
	
	
	static func from_json(d: Dictionary) -> Emote:
		var result: Emote = Emote.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("emote_set_id", null) != null:
			result.emote_set_id = d["emote_set_id"]
		if d.get("owner_id", null) != null:
			result.owner_id = d["owner_id"]
		if d.get("format", null) != null:
			for value in d["format"]:
				result.format.append(value)
		return result
	


## Optional. Metadata pertaining to the mention.
## #/components/schemas/ChannelChatMessageEvent/Message/Fragments/Mention
class Mention extends TwitchData:

	## The user ID of the mentioned user.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The user name of the mentioned user.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The user login of the mentioned user.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	
	
	static func from_json(d: Dictionary) -> Mention:
		var result: Mention = Mention.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		return result
	


## List of chat badges.
## #/components/schemas/ChannelChatMessageEvent/Badges
class Badges extends TwitchData:

	## An ID that identifies this set of chat badges. For example, Bits or Subscriber.
	@export var set_id: String:
		set(val): 
			set_id = val
			track_data(&"set_id", val)
	
	## An ID that identifies this version of the badge. The ID can be any value. For example, for Bits, the ID is the Bits tier level, but for World of Warcraft, it could be Alliance or Horde.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## Contains metadata related to the chat badges in the badges tag. Currently, this tag contains metadata only for subscriber badges, to indicate the number of months the user has been a subscriber.
	@export var info: String:
		set(val): 
			info = val
			track_data(&"info", val)
	
	
	
	static func from_json(d: Dictionary) -> Badges:
		var result: Badges = Badges.new()
		if d.get("set_id", null) != null:
			result.set_id = d["set_id"]
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("info", null) != null:
			result.info = d["info"]
		return result
	


## Optional. Metadata if this message is a cheer.
## #/components/schemas/ChannelChatMessageEvent/Cheer
class Cheer extends TwitchData:

	## The amount of Bits the user cheered.
	@export var bits: int:
		set(val): 
			bits = val
			track_data(&"bits", val)
	
	
	
	static func from_json(d: Dictionary) -> Cheer:
		var result: Cheer = Cheer.new()
		if d.get("bits", null) != null:
			result.bits = d["bits"]
		return result
	


## Optional. Metadata if this message is a reply.
## #/components/schemas/ChannelChatMessageEvent/Reply
class Reply extends TwitchData:

	## An ID that uniquely identifies the parent message that this message is replying to.
	@export var parent_message_id: String:
		set(val): 
			parent_message_id = val
			track_data(&"parent_message_id", val)
	
	## The message body of the parent message.
	@export var parent_message_body: String:
		set(val): 
			parent_message_body = val
			track_data(&"parent_message_body", val)
	
	## User ID of the sender of the parent message.
	@export var parent_user_id: String:
		set(val): 
			parent_user_id = val
			track_data(&"parent_user_id", val)
	
	## User name of the sender of the parent message.
	@export var parent_user_name: String:
		set(val): 
			parent_user_name = val
			track_data(&"parent_user_name", val)
	
	## User login of the sender of the parent message.
	@export var parent_user_login: String:
		set(val): 
			parent_user_login = val
			track_data(&"parent_user_login", val)
	
	## An ID that identifies the parent message of the reply thread.
	@export var thread_message_id: String:
		set(val): 
			thread_message_id = val
			track_data(&"thread_message_id", val)
	
	## User ID of the sender of the thread’s parent message.
	@export var thread_user_id: String:
		set(val): 
			thread_user_id = val
			track_data(&"thread_user_id", val)
	
	## User name of the sender of the thread’s parent message.
	@export var thread_user_name: String:
		set(val): 
			thread_user_name = val
			track_data(&"thread_user_name", val)
	
	## User login of the sender of the thread’s parent message.
	@export var thread_user_login: String:
		set(val): 
			thread_user_login = val
			track_data(&"thread_user_login", val)
	
	
	
	static func from_json(d: Dictionary) -> Reply:
		var result: Reply = Reply.new()
		if d.get("parent_message_id", null) != null:
			result.parent_message_id = d["parent_message_id"]
		if d.get("parent_message_body", null) != null:
			result.parent_message_body = d["parent_message_body"]
		if d.get("parent_user_id", null) != null:
			result.parent_user_id = d["parent_user_id"]
		if d.get("parent_user_name", null) != null:
			result.parent_user_name = d["parent_user_name"]
		if d.get("parent_user_login", null) != null:
			result.parent_user_login = d["parent_user_login"]
		if d.get("thread_message_id", null) != null:
			result.thread_message_id = d["thread_message_id"]
		if d.get("thread_user_id", null) != null:
			result.thread_user_id = d["thread_user_id"]
		if d.get("thread_user_name", null) != null:
			result.thread_user_name = d["thread_user_name"]
		if d.get("thread_user_login", null) != null:
			result.thread_user_login = d["thread_user_login"]
		return result
	


## Optional. The list of chat badges for the chatter in the channel the message was sent from. Is null when the message happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
## #/components/schemas/ChannelChatMessageEvent/SourceBadges
class SourceBadges extends TwitchData:

	## The ID that identifies this set of chat badges. For example, Bits or Subscriber.
	@export var set_id: String:
		set(val): 
			set_id = val
			track_data(&"set_id", val)
	
	## The ID that identifies this version of the badge. The ID can be any value. For example, for Bits, the ID is the Bits tier level, but for World of Warcraft, it could be Alliance or Horde.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## Contains metadata related to the chat badges in the badges tag. Currently, this tag contains metadata only for subscriber badges, to indicate the number of months the user has been a subscriber.
	@export var info: String:
		set(val): 
			info = val
			track_data(&"info", val)
	
	
	
	static func from_json(d: Dictionary) -> SourceBadges:
		var result: SourceBadges = SourceBadges.new()
		if d.get("set_id", null) != null:
			result.set_id = d["set_id"]
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("info", null) != null:
			result.info = d["info"]
		return result
	