@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelPointsAutomaticRewardRedemptionAdd
	


## 
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddCondition
class Condition extends TwitchData:

	## The broadcaster user ID for the channel you want to receive channel points reward add notifications for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddV2Condition
class V2Condition extends TwitchData:

	## The broadcaster user ID for the channel you want to receive channel points reward add notifications for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> V2Condition:
		var result: V2Condition = V2Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddEvent
class Event extends TwitchData:

	## The ID of the channel where the reward was redeemed.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The login of the channel where the reward was redeemed.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The display name of the channel where the reward was redeemed.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The ID of the redeeming user.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the redeeming user.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The display name of the redeeming user.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The ID of the Redemption.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## An object that contains the reward information.
	@export var reward: Reward:
		set(val): 
			reward = val
			track_data(&"reward", val)
	
	## An object that contains the user message and emote information needed to recreate the message.
	@export var message: Message:
		set(val): 
			message = val
			track_data(&"message", val)
	
	## Optional. A string that the user entered if the reward requires input.
	@export var user_input: String:
		set(val): 
			user_input = val
			track_data(&"user_input", val)
	
	## The UTC date and time (in RFC3339 format) of when the reward was redeemed.
	@export var redeemed_at: String:
		set(val): 
			redeemed_at = val
			track_data(&"redeemed_at", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("reward", null) != null:
			result.reward = Reward.from_json(d["reward"])
		if d.get("message", null) != null:
			result.message = Message.from_json(d["message"])
		if d.get("user_input", null) != null:
			result.user_input = d["user_input"]
		if d.get("redeemed_at", null) != null:
			result.redeemed_at = d["redeemed_at"]
		return result
	


## An object that contains the reward information.
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddEvent/Reward
class Reward extends TwitchData:

	## The type of reward. One of: single_message_bypass_sub_modesend_highlighted_messagerandom_sub_emote_unlockchosen_sub_emote_unlockchosen_modified_sub_emote_unlockmessage_effectgigantify_an_emotecelebration
	@export var type: String:
		set(val): 
			type = val
			track_data(&"type", val)
	
	## The reward cost.
	@export var cost: int:
		set(val): 
			cost = val
			track_data(&"cost", val)
	
	## Optional. Emote that was unlocked.
	@export var unlocked_emote: UnlockedEmote:
		set(val): 
			unlocked_emote = val
			track_data(&"unlocked_emote", val)
	
	
	
	static func from_json(d: Dictionary) -> Reward:
		var result: Reward = Reward.new()
		if d.get("type", null) != null:
			result.type = d["type"]
		if d.get("cost", null) != null:
			result.cost = d["cost"]
		if d.get("unlocked_emote", null) != null:
			result.unlocked_emote = UnlockedEmote.from_json(d["unlocked_emote"])
		return result
	


## Optional. Emote that was unlocked.
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddEvent/Reward/UnlockedEmote
class UnlockedEmote extends TwitchData:

	## The emote ID.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## The human readable emote token.
	@export var name: String:
		set(val): 
			name = val
			track_data(&"name", val)
	
	
	
	static func from_json(d: Dictionary) -> UnlockedEmote:
		var result: UnlockedEmote = UnlockedEmote.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("name", null) != null:
			result.name = d["name"]
		return result
	


## An object that contains the user message and emote information needed to recreate the message.
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddEvent/Message
class Message extends TwitchData:

	## The text of the chat message.
	@export var text: String:
		set(val): 
			text = val
			track_data(&"text", val)
	
	## An array that includes the emote ID and start and end positions for where the emote appears in the text.
	@export var emotes: Array[Emotes]:
		set(val): 
			emotes = val
			track_data(&"emotes", val)
	
	
	
	static func from_json(d: Dictionary) -> Message:
		var result: Message = Message.new()
		if d.get("text", null) != null:
			result.text = d["text"]
		if d.get("emotes", null) != null:
			for value in d["emotes"]:
				result.emotes.append(Emotes.from_json(value))
		return result
	


## An array that includes the emote ID and start and end positions for where the emote appears in the text.
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddEvent/Message/Emotes
class Emotes extends TwitchData:

	## The emote ID.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## The index of where the Emote starts in the text.
	@export var begin: int:
		set(val): 
			begin = val
			track_data(&"begin", val)
	
	## The index of where the Emote ends in the text.
	@export var end: int:
		set(val): 
			end = val
			track_data(&"end", val)
	
	
	
	static func from_json(d: Dictionary) -> Emotes:
		var result: Emotes = Emotes.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("begin", null) != null:
			result.begin = d["begin"]
		if d.get("end", null) != null:
			result.end = d["end"]
		return result
	


## 
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddV2Event
class V2Event extends TwitchData:

	## The ID of the channel where the reward was redeemed.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The login of the channel where the reward was redeemed.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The display name of the channel where the reward was redeemed.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The ID of the redeeming user.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the redeeming user.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The display name of the redeeming user.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The ID of the Redemption.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## An object that contains the reward information.
	@export var reward: RewardV2:
		set(val): 
			reward = val
			track_data(&"reward", val)
	
	## Optional. An object that contains the user message and emote information needed to recreate the message.
	@export var message: MessageV2:
		set(val): 
			message = val
			track_data(&"message", val)
	
	## The UTC date and time (in RFC3339 format) of when the reward was redeemed.
	@export var redeemed_at: String:
		set(val): 
			redeemed_at = val
			track_data(&"redeemed_at", val)
	
	
	
	static func from_json(d: Dictionary) -> V2Event:
		var result: V2Event = V2Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("reward", null) != null:
			result.reward = RewardV2.from_json(d["reward"])
		if d.get("message", null) != null:
			result.message = MessageV2.from_json(d["message"])
		if d.get("redeemed_at", null) != null:
			result.redeemed_at = d["redeemed_at"]
		return result
	


## An object that contains the reward information.
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddV2Event/Reward
class RewardV2 extends TwitchData:

	## The type of reward. One of: single_message_bypass_sub_modesend_highlighted_messagerandom_sub_emote_unlockchosen_sub_emote_unlockchosen_modified_sub_emote_unlock
	@export var type: String:
		set(val): 
			type = val
			track_data(&"type", val)
	
	## Number of channel points used.
	@export var channel_points: int:
		set(val): 
			channel_points = val
			track_data(&"channel_points", val)
	
	## Optional. Emote associated with the reward.
	@export var emote: EmoteV2:
		set(val): 
			emote = val
			track_data(&"emote", val)
	
	
	
	static func from_json(d: Dictionary) -> RewardV2:
		var result: RewardV2 = RewardV2.new()
		if d.get("type", null) != null:
			result.type = d["type"]
		if d.get("channel_points", null) != null:
			result.channel_points = d["channel_points"]
		if d.get("emote", null) != null:
			result.emote = EmoteV2.from_json(d["emote"])
		return result
	


## Optional. Emote associated with the reward.
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddV2Event/Reward/Emote
class EmoteV2 extends TwitchData:

	## The emote ID.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## The human readable emote token.
	@export var name: String:
		set(val): 
			name = val
			track_data(&"name", val)
	
	
	
	static func from_json(d: Dictionary) -> EmoteV2:
		var result: EmoteV2 = EmoteV2.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("name", null) != null:
			result.name = d["name"]
		return result
	


## Optional. An object that contains the user message and emote information needed to recreate the message.
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddV2Event/Message
class MessageV2 extends TwitchData:

	## The chat message in plain text.
	@export var text: String:
		set(val): 
			text = val
			track_data(&"text", val)
	
	## The ordered list of chat message fragments.
	@export var fragments: Array[FragmentsV2]:
		set(val): 
			fragments = val
			track_data(&"fragments", val)
	
	
	
	static func from_json(d: Dictionary) -> MessageV2:
		var result: MessageV2 = MessageV2.new()
		if d.get("text", null) != null:
			result.text = d["text"]
		if d.get("fragments", null) != null:
			for value in d["fragments"]:
				result.fragments.append(FragmentsV2.from_json(value))
		return result
	


## The ordered list of chat message fragments.
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddV2Event/Message/Fragments
class FragmentsV2 extends TwitchData:

	## The message text in fragment.
	@export var text: String:
		set(val): 
			text = val
			track_data(&"text", val)
	
	## The type of message fragment. Possible values are: textemote
	@export var type: String:
		set(val): 
			type = val
			track_data(&"type", val)
	
	## Optional. The metadata pertaining to the emote.
	@export var emote: Fragments_EmoteV2:
		set(val): 
			emote = val
			track_data(&"emote", val)
	
	
	
	static func from_json(d: Dictionary) -> FragmentsV2:
		var result: FragmentsV2 = FragmentsV2.new()
		if d.get("text", null) != null:
			result.text = d["text"]
		if d.get("type", null) != null:
			result.type = d["type"]
		if d.get("emote", null) != null:
			result.emote = Fragments_EmoteV2.from_json(d["emote"])
		return result
	


## Optional. The metadata pertaining to the emote.
## #/components/schemas/ChannelPointsAutomaticRewardRedemptionAddV2Event/Message/Fragments/Emote
class Fragments_EmoteV2 extends TwitchData:

	## The ID that uniquely identifies this emote.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	
	
	static func from_json(d: Dictionary) -> Fragments_EmoteV2:
		var result: Fragments_EmoteV2 = Fragments_EmoteV2.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		return result
	
