@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/Subscription
class_name TwitchESSubscription
	
## Your client ID.
@export var id: String:
	set(val): 
		id = val
		track_data(&"id", val)

## The notification’s subscription type.
@export var type: String:
	set(val): 
		type = val
		track_data(&"type", val)

## The version of the subscription.
@export var version: String:
	set(val): 
		version = val
		track_data(&"version", val)

## The status of the subscription.
@export var status: String:
	set(val): 
		status = val
		track_data(&"status", val)

## How much the subscription counts against your limit. See Subscription Limits for more information.
@export var cost: int:
	set(val): 
		cost = val
		track_data(&"cost", val)

## Subscription-specific parameters.
@export var condition: Dictionary:
	set(val): 
		condition = val
		track_data(&"condition", val)

## The time the notification was created.
@export var created_at: String:
	set(val): 
		created_at = val
		track_data(&"created_at", val)

## Transport details.
@export var transport: TwitchESTransport:
	set(val): 
		transport = val
		track_data(&"transport", val)



static func from_json(d: Dictionary) -> TwitchESSubscription:
	var result: TwitchESSubscription = TwitchESSubscription.new()
	if d.get("id", null) != null:
		result.id = d["id"]
	if d.get("type", null) != null:
		result.type = d["type"]
	if d.get("version", null) != null:
		result.version = d["version"]
	if d.get("status", null) != null:
		result.status = d["status"]
	if d.get("cost", null) != null:
		result.cost = d["cost"]
	if d.get("condition", null) != null:
		result.condition = d["condition"]
	if d.get("created_at", null) != null:
		result.created_at = d["created_at"]
	if d.get("transport", null) != null:
		result.transport = TwitchESTransport.from_json(d["transport"])
	return result
