@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESExtensionBitsTransactionCreate
	


## 
## #/components/schemas/ExtensionBitsTransactionCreateCondition
class Condition extends TwitchData:

	## The client ID of the extension.
	@export var extension_client_id: String:
		set(val): 
			extension_client_id = val
			track_data(&"extension_client_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("extension_client_id", null) != null:
			result.extension_client_id = d["extension_client_id"]
		return result
	


## 
## #/components/schemas/ExtensionBitsTransactionCreateEvent
class Event extends TwitchData:

	## Client ID of the extension.
	@export var extension_client_id: String:
		set(val): 
			extension_client_id = val
			track_data(&"extension_client_id", val)
	
	## Transaction ID.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## The transaction’s broadcaster ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The transaction’s broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The transaction’s broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The transaction’s user ID.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The transaction’s user login.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The transaction’s user display name.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## Additional extension product information.
	@export var product: TwitchESProduct:
		set(val): 
			product = val
			track_data(&"product", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("extension_client_id", null) != null:
			result.extension_client_id = d["extension_client_id"]
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("product", null) != null:
			result.product = TwitchESProduct.from_json(d["product"])
		return result
	