@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESAutomodSettingsUpdate
	


## 
## #/components/schemas/AutomodSettingsUpdateCondition
class Condition extends TwitchData:

	## User ID of the broadcaster (channel). Maximum:1.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## User ID of the moderator.
	@export var moderator_user_id: String:
		set(val): 
			moderator_user_id = val
			track_data(&"moderator_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("moderator_user_id", null) != null:
			result.moderator_user_id = d["moderator_user_id"]
		return result
	


## 
## #/components/schemas/AutomodSettingsUpdateEvent
class Event extends TwitchData:

	## The ID of the broadcaster specified in the request.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The login of the broadcaster specified in the request.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The user name of the broadcaster specified in the request.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The ID of the moderator who changed the channel settings.
	@export var moderator_user_id: String:
		set(val): 
			moderator_user_id = val
			track_data(&"moderator_user_id", val)
	
	## The moderator’s login.
	@export var moderator_user_login: String:
		set(val): 
			moderator_user_login = val
			track_data(&"moderator_user_login", val)
	
	## The moderator’s user name.
	@export var moderator_user_name: String:
		set(val): 
			moderator_user_name = val
			track_data(&"moderator_user_name", val)
	
	## The Automod level for hostility involving name calling or insults.
	@export var bullying: int:
		set(val): 
			bullying = val
			track_data(&"bullying", val)
	
	## The default AutoMod level for the broadcaster. This field is null if the broadcaster has set one or more of the individual settings.
	@export var overall_level: int:
		set(val): 
			overall_level = val
			track_data(&"overall_level", val)
	
	## The Automod level for discrimination against disability.
	@export var disability: int:
		set(val): 
			disability = val
			track_data(&"disability", val)
	
	## The Automod level for racial discrimination.
	@export var race_ethnicity_or_religion: int:
		set(val): 
			race_ethnicity_or_religion = val
			track_data(&"race_ethnicity_or_religion", val)
	
	## The Automod level for discrimination against women.
	@export var misogyny: int:
		set(val): 
			misogyny = val
			track_data(&"misogyny", val)
	
	## The AutoMod level for discrimination based on sexuality, sex, or gender.
	@export var sexuality_sex_or_gender: int:
		set(val): 
			sexuality_sex_or_gender = val
			track_data(&"sexuality_sex_or_gender", val)
	
	## The Automod level for hostility involving aggression.
	@export var aggression: int:
		set(val): 
			aggression = val
			track_data(&"aggression", val)
	
	## The Automod level for sexual content.
	@export var sex_based_terms: int:
		set(val): 
			sex_based_terms = val
			track_data(&"sex_based_terms", val)
	
	## The Automod level for profanity.
	@export var swearing: int:
		set(val): 
			swearing = val
			track_data(&"swearing", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("moderator_user_id", null) != null:
			result.moderator_user_id = d["moderator_user_id"]
		if d.get("moderator_user_login", null) != null:
			result.moderator_user_login = d["moderator_user_login"]
		if d.get("moderator_user_name", null) != null:
			result.moderator_user_name = d["moderator_user_name"]
		if d.get("bullying", null) != null:
			result.bullying = d["bullying"]
		if d.get("overall_level", null) != null:
			result.overall_level = d["overall_level"]
		if d.get("disability", null) != null:
			result.disability = d["disability"]
		if d.get("race_ethnicity_or_religion", null) != null:
			result.race_ethnicity_or_religion = d["race_ethnicity_or_religion"]
		if d.get("misogyny", null) != null:
			result.misogyny = d["misogyny"]
		if d.get("sexuality_sex_or_gender", null) != null:
			result.sexuality_sex_or_gender = d["sexuality_sex_or_gender"]
		if d.get("aggression", null) != null:
			result.aggression = d["aggression"]
		if d.get("sex_based_terms", null) != null:
			result.sex_based_terms = d["sex_based_terms"]
		if d.get("swearing", null) != null:
			result.swearing = d["swearing"]
		return result
	