@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESWhisperReceived
	


## 
## #/components/schemas/WhisperReceivedCondition
class Condition extends TwitchData:

	## The user_id of the person receiving whispers.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		return result
	


## 
## #/components/schemas/WhisperReceivedEvent
class Event extends TwitchData:

	## The ID of the user sending the message.
	@export var from_user_id: String:
		set(val): 
			from_user_id = val
			track_data(&"from_user_id", val)
	
	## The name of the user sending the message.
	@export var from_user_name: String:
		set(val): 
			from_user_name = val
			track_data(&"from_user_name", val)
	
	## The login of the user sending the message.
	@export var from_user_login: String:
		set(val): 
			from_user_login = val
			track_data(&"from_user_login", val)
	
	## The ID of the user receiving the message.
	@export var to_user_id: String:
		set(val): 
			to_user_id = val
			track_data(&"to_user_id", val)
	
	## The name of the user receiving the message.
	@export var to_user_name: String:
		set(val): 
			to_user_name = val
			track_data(&"to_user_name", val)
	
	## The login of the user receiving the message.
	@export var to_user_login: String:
		set(val): 
			to_user_login = val
			track_data(&"to_user_login", val)
	
	## The whisper ID.
	@export var whisper_id: String:
		set(val): 
			whisper_id = val
			track_data(&"whisper_id", val)
	
	## Object containing whisper information.
	@export var whisper: Whisper:
		set(val): 
			whisper = val
			track_data(&"whisper", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("from_user_id", null) != null:
			result.from_user_id = d["from_user_id"]
		if d.get("from_user_name", null) != null:
			result.from_user_name = d["from_user_name"]
		if d.get("from_user_login", null) != null:
			result.from_user_login = d["from_user_login"]
		if d.get("to_user_id", null) != null:
			result.to_user_id = d["to_user_id"]
		if d.get("to_user_name", null) != null:
			result.to_user_name = d["to_user_name"]
		if d.get("to_user_login", null) != null:
			result.to_user_login = d["to_user_login"]
		if d.get("whisper_id", null) != null:
			result.whisper_id = d["whisper_id"]
		if d.get("whisper", null) != null:
			result.whisper = Whisper.from_json(d["whisper"])
		return result
	


## Object containing whisper information.
## #/components/schemas/WhisperReceivedEvent/Whisper
class Whisper extends TwitchData:

	## The body of the whisper message.
	@export var text: String:
		set(val): 
			text = val
			track_data(&"text", val)
	
	
	
	static func from_json(d: Dictionary) -> Whisper:
		var result: Whisper = Whisper.new()
		if d.get("text", null) != null:
			result.text = d["text"]
		return result
	