@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelCustomPowerUpRedemptionAdd
	


## 
## #/components/schemas/ChannelCustomPowerUpRedemptionAddCondition
class Condition extends TwitchData:

	## The broadcaster user ID for the channel you want to receive custom Power-up redemption add notifications for.
	@export var broadcaster_user_id: String:
		set(val):
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## Optional . Specify a reward id to only receive notifications for a specific custom Power-up.
	@export var reward_id: String:
		set(val):
			reward_id = val
			track_data(&"reward_id", val)
	
	
	
	## Constructor with all required fields.
	static func create(_broadcaster_user_id: String) -> Condition:
		var condition: Condition = Condition.new()
		condition.broadcaster_user_id = _broadcaster_user_id
		return condition
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("reward_id", null) != null:
			result.reward_id = d["reward_id"]
		return result
	


## 
## #/components/schemas/ChannelCustomPowerUpRedemptionAddEvent
class Event extends TwitchData:

	## The redemption identifier.
	@export var id: String:
		set(val):
			id = val
			track_data(&"id", val)
	
	## The requested broadcaster ID.
	@export var broadcaster_user_id: String:
		set(val):
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The requested broadcaster login.
	@export var broadcaster_user_login: String:
		set(val):
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The requested broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val):
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## User ID of the user that redeemed the custom Power-up.
	@export var user_id: String:
		set(val):
			user_id = val
			track_data(&"user_id", val)
	
	## Login of the user that redeemed the custom Power-up.
	@export var user_login: String:
		set(val):
			user_login = val
			track_data(&"user_login", val)
	
	## Display name of the user that redeemed the custom Power-up.
	@export var user_name: String:
		set(val):
			user_name = val
			track_data(&"user_name", val)
	
	## The user input provided. Empty string if not provided.
	@export var user_input: String:
		set(val):
			user_input = val
			track_data(&"user_input", val)
	
	## Defaults to unfulfilled . Possible values are unknown , unfulfilled , fulfilled , and canceled .
	@export var status: String:
		set(val):
			status = val
			track_data(&"status", val)
	
	## Basic information about the custom Power-up that was redeemed, at the time it was redeemed.
	@export var custom_power_up: TwitchESCustomPowerUp:
		set(val):
			custom_power_up = val
			track_data(&"custom_power_up", val)
	
	## RFC3339 timestamp of when the custom Power-up was redeemed.
	@export var redeemed_at: String:
		set(val):
			redeemed_at = val
			track_data(&"redeemed_at", val)
	
	
	
	## Constructor with all required fields.
	static func create() -> Event:
		var event: Event = Event.new()
		return event
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("user_input", null) != null:
			result.user_input = d["user_input"]
		if d.get("status", null) != null:
			result.status = d["status"]
		if d.get("custom_power_up", null) != null:
			result.custom_power_up = TwitchESCustomPowerUp.from_json(d["custom_power_up"])
		if d.get("redeemed_at", null) != null:
			result.redeemed_at = d["redeemed_at"]
		return result
	
