@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESUserAuthorizationRevoke
	


## 
## #/components/schemas/UserAuthorizationRevokeCondition
class Condition extends TwitchData:

	## Your application’s client id. The provided client_id must match the client id in the application access token.
	@export var client_id: String:
		set(val): 
			client_id = val
			track_data(&"client_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("client_id", null) != null:
			result.client_id = d["client_id"]
		return result
	


## 
## #/components/schemas/UserAuthorizationRevokeEvent
class Event extends TwitchData:

	## The client_id of the application with revoked user access.
	@export var client_id: String:
		set(val): 
			client_id = val
			track_data(&"client_id", val)
	
	## The user id for the user who has revoked authorization for your client id.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The user login for the user who has revoked authorization for your client id. This is null if the user no longer exists.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user display name for the user who has revoked authorization for your client id. This is null if the user no longer exists.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("client_id", null) != null:
			result.client_id = d["client_id"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	