@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESConduitShardDisabled
	


## 
## #/components/schemas/ConduitShardDisabledCondition
class Condition extends TwitchData:

	## Your application’s client id. The provided client_id must match the client ID in the application access token.
	@export var client_id: String:
		set(val): 
			client_id = val
			track_data(&"client_id", val)
	
	## The conduit ID to receive events for. If omitted, events for all of this client’s conduits are sent.
	@export var conduit_id: String:
		set(val): 
			conduit_id = val
			track_data(&"conduit_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("client_id", null) != null:
			result.client_id = d["client_id"]
		if d.get("conduit_id", null) != null:
			result.conduit_id = d["conduit_id"]
		return result
	


## 
## #/components/schemas/ConduitShardDisabledEvent
class Event extends TwitchData:

	## The ID of the conduit.
	@export var conduit_id: String:
		set(val): 
			conduit_id = val
			track_data(&"conduit_id", val)
	
	## The ID of the disabled shard.
	@export var shard_id: String:
		set(val): 
			shard_id = val
			track_data(&"shard_id", val)
	
	## The new status of the transport.
	@export var status: String:
		set(val): 
			status = val
			track_data(&"status", val)
	
	## The disabled transport.
	@export var transport: Dictionary:
		set(val): 
			transport = val
			track_data(&"transport", val)
	
	## websocket or webhook
	@export var method: String:
		set(val): 
			method = val
			track_data(&"method", val)
	
	## Optional. Webhook callback URL. Null if method is set to websocket.
	@export var callback: String:
		set(val): 
			callback = val
			track_data(&"callback", val)
	
	## Optional. WebSocket session ID. Null if method is set to webhook.
	@export var session_id: String:
		set(val): 
			session_id = val
			track_data(&"session_id", val)
	
	## Optional. Time that the WebSocket session connected. Null if method is set to webhook.
	@export var connected_at: String:
		set(val): 
			connected_at = val
			track_data(&"connected_at", val)
	
	## Optional. Time that the WebSocket session disconnected. Null if method is set to webhook.
	@export var disconnected_at: String:
		set(val): 
			disconnected_at = val
			track_data(&"disconnected_at", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("conduit_id", null) != null:
			result.conduit_id = d["conduit_id"]
		if d.get("shard_id", null) != null:
			result.shard_id = d["shard_id"]
		if d.get("status", null) != null:
			result.status = d["status"]
		if d.get("transport", null) != null:
			result.transport = d["transport"]
		if d.get("method", null) != null:
			result.method = d["method"]
		if d.get("callback", null) != null:
			result.callback = d["callback"]
		if d.get("session_id", null) != null:
			result.session_id = d["session_id"]
		if d.get("connected_at", null) != null:
			result.connected_at = d["connected_at"]
		if d.get("disconnected_at", null) != null:
			result.disconnected_at = d["disconnected_at"]
		return result
	