@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelSubscriptionMessage
	


## 
## #/components/schemas/ChannelSubscriptionMessageCondition
class Condition extends TwitchData:

	## The broadcaster user ID for the channel you want to get resubscription chat message notifications for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelSubscriptionMessageEvent
class Event extends TwitchData:

	## The user ID of the user who sent a resubscription chat message.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The user login of the user who sent a resubscription chat message.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user display name of the user who a resubscription chat message.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The broadcaster user ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The tier of the user’s subscription.
	@export var tier: String:
		set(val): 
			tier = val
			track_data(&"tier", val)
	
	## An object that contains the resubscription message and emote information needed to recreate the message.
	@export var message: TwitchESMessage:
		set(val): 
			message = val
			track_data(&"message", val)
	
	## The total number of months the user has been subscribed to the channel.
	@export var cumulative_months: int:
		set(val): 
			cumulative_months = val
			track_data(&"cumulative_months", val)
	
	## The number of consecutive months the user’s current subscription has been active. This value is null if the user has opted out of sharing this information.
	@export var streak_months: int:
		set(val): 
			streak_months = val
			track_data(&"streak_months", val)
	
	## The month duration of the subscription.
	@export var duration_months: int:
		set(val): 
			duration_months = val
			track_data(&"duration_months", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("tier", null) != null:
			result.tier = d["tier"]
		if d.get("message", null) != null:
			result.message = TwitchESMessage.from_json(d["message"])
		if d.get("cumulative_months", null) != null:
			result.cumulative_months = d["cumulative_months"]
		if d.get("streak_months", null) != null:
			result.streak_months = d["streak_months"]
		if d.get("duration_months", null) != null:
			result.duration_months = d["duration_months"]
		return result
	