@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelSubscriptionGift
	


## 
## #/components/schemas/ChannelSubscriptionGiftCondition
class Condition extends TwitchData:

	## The broadcaster user ID for the channel you want to get subscription gift notifications for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelSubscriptionGiftEvent
class Event extends TwitchData:

	## The user ID of the user who sent the subscription gift. Set to null if it was an anonymous subscription gift.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The user login of the user who sent the gift. Set to null if it was an anonymous subscription gift.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user display name of the user who sent the gift. Set to null if it was an anonymous subscription gift.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The broadcaster user ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The number of subscriptions in the subscription gift.
	@export var total: int:
		set(val): 
			total = val
			track_data(&"total", val)
	
	## The tier of subscriptions in the subscription gift.
	@export var tier: String:
		set(val): 
			tier = val
			track_data(&"tier", val)
	
	## The number of subscriptions gifted by this user in the channel. This value is null for anonymous gifts or if the gifter has opted out of sharing this information.
	@export var cumulative_total: int:
		set(val): 
			cumulative_total = val
			track_data(&"cumulative_total", val)
	
	## Whether the subscription gift was anonymous.
	@export var is_anonymous: bool:
		set(val): 
			is_anonymous = val
			track_data(&"is_anonymous", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("total", null) != null:
			result.total = d["total"]
		if d.get("tier", null) != null:
			result.tier = d["tier"]
		if d.get("cumulative_total", null) != null:
			result.cumulative_total = d["cumulative_total"]
		if d.get("is_anonymous", null) != null:
			result.is_anonymous = d["is_anonymous"]
		return result
	