@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelGuestStarGuestUpdate
	


## 
## #/components/schemas/ChannelGuestStarGuestUpdateCondition
class Condition extends TwitchData:

	## The broadcaster user ID of the channel hosting the Guest Star Session
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The user ID of the moderator or broadcaster of the specified channel.
	@export var moderator_user_id: String:
		set(val): 
			moderator_user_id = val
			track_data(&"moderator_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("moderator_user_id", null) != null:
			result.moderator_user_id = d["moderator_user_id"]
		return result
	


## 
## #/components/schemas/ChannelGuestStarGuestUpdateEvent
class Event extends TwitchData:

	## The non-host broadcaster user ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The non-host broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The non-host broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## ID representing the unique session that was started.
	@export var session_id: String:
		set(val): 
			session_id = val
			track_data(&"session_id", val)
	
	## The user ID of the moderator who updated the guest’s state (could be the host). null if the update was performed by the guest.
	@export var moderator_user_id: String:
		set(val): 
			moderator_user_id = val
			track_data(&"moderator_user_id", val)
	
	## The moderator display name.null if the update was performed by the guest.
	@export var moderator_user_name: String:
		set(val): 
			moderator_user_name = val
			track_data(&"moderator_user_name", val)
	
	## The moderator login. null if the update was performed by the guest.
	@export var moderator_user_login: String:
		set(val): 
			moderator_user_login = val
			track_data(&"moderator_user_login", val)
	
	## The user ID of the guest who transitioned states in the session. null if the slot is now empty.
	@export var guest_user_id: String:
		set(val): 
			guest_user_id = val
			track_data(&"guest_user_id", val)
	
	## The guest display name. null if the slot is now empty.
	@export var guest_user_name: String:
		set(val): 
			guest_user_name = val
			track_data(&"guest_user_name", val)
	
	## The guest login. null if the slot is now empty.
	@export var guest_user_login: String:
		set(val): 
			guest_user_login = val
			track_data(&"guest_user_login", val)
	
	## The ID of the slot assignment the guest is assigned to. null if the guest is in the INVITED, REMOVED, READY, or ACCEPTED state.
	@export var slot_id: String:
		set(val): 
			slot_id = val
			track_data(&"slot_id", val)
	
	## The current state of the user after the update has taken place. null if the slot is now empty. Can otherwise be one of the following: invited — The guest has transitioned to the invite queue. This can take place when the guest was previously assigned a slot, but have been removed from the call and are sent back to the invite queue.accepted — The guest has accepted the invite and is currently in the process of setting up to join the session.ready — The guest has signaled they are ready and can be assigned a slot.backstage — The guest has been assigned a slot in the session, but is not currently seen live in the broadcasting software.live — The guest is now live in the host's broadcasting software.removed — The guest was removed from the call or queue.accepted — The guest has accepted the invite to the call.
	@export var state: String:
		set(val): 
			state = val
			track_data(&"state", val)
	
	## User ID of the host channel.
	@export var host_user_id: String:
		set(val): 
			host_user_id = val
			track_data(&"host_user_id", val)
	
	## The host display name.
	@export var host_user_name: String:
		set(val): 
			host_user_name = val
			track_data(&"host_user_name", val)
	
	## The host login.
	@export var host_user_login: String:
		set(val): 
			host_user_login = val
			track_data(&"host_user_login", val)
	
	## Flag that signals whether the host is allowing the slot’s video to be seen by participants within the session. null if the guest is not slotted.
	@export var host_video_enabled: bool:
		set(val): 
			host_video_enabled = val
			track_data(&"host_video_enabled", val)
	
	## Flag that signals whether the host is allowing the slot’s audio to be heard by participants within the session. null if the guest is not slotted.
	@export var host_audio_enabled: bool:
		set(val): 
			host_audio_enabled = val
			track_data(&"host_audio_enabled", val)
	
	## Value between 0-100 that represents the slot’s audio level as heard by participants within the session. null if the guest is not slotted.
	@export var host_volume: int:
		set(val): 
			host_volume = val
			track_data(&"host_volume", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("session_id", null) != null:
			result.session_id = d["session_id"]
		if d.get("moderator_user_id", null) != null:
			result.moderator_user_id = d["moderator_user_id"]
		if d.get("moderator_user_name", null) != null:
			result.moderator_user_name = d["moderator_user_name"]
		if d.get("moderator_user_login", null) != null:
			result.moderator_user_login = d["moderator_user_login"]
		if d.get("guest_user_id", null) != null:
			result.guest_user_id = d["guest_user_id"]
		if d.get("guest_user_name", null) != null:
			result.guest_user_name = d["guest_user_name"]
		if d.get("guest_user_login", null) != null:
			result.guest_user_login = d["guest_user_login"]
		if d.get("slot_id", null) != null:
			result.slot_id = d["slot_id"]
		if d.get("state", null) != null:
			result.state = d["state"]
		if d.get("host_user_id", null) != null:
			result.host_user_id = d["host_user_id"]
		if d.get("host_user_name", null) != null:
			result.host_user_name = d["host_user_name"]
		if d.get("host_user_login", null) != null:
			result.host_user_login = d["host_user_login"]
		if d.get("host_video_enabled", null) != null:
			result.host_video_enabled = d["host_video_enabled"]
		if d.get("host_audio_enabled", null) != null:
			result.host_audio_enabled = d["host_audio_enabled"]
		if d.get("host_volume", null) != null:
			result.host_volume = d["host_volume"]
		return result
	