@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/Reward
class_name TwitchESReward
	
## The reward identifier.
@export var id: String:
	set(val): 
		id = val
		track_data(&"id", val)

## The reward name.
@export var title: String:
	set(val): 
		title = val
		track_data(&"title", val)

## The reward cost.
@export var cost: int:
	set(val): 
		cost = val
		track_data(&"cost", val)

## The reward description.
@export var prompt: String:
	set(val): 
		prompt = val
		track_data(&"prompt", val)



static func from_json(d: Dictionary) -> TwitchESReward:
	var result: TwitchESReward = TwitchESReward.new()
	if d.get("id", null) != null:
		result.id = d["id"]
	if d.get("title", null) != null:
		result.title = d["title"]
	if d.get("cost", null) != null:
		result.cost = d["cost"]
	if d.get("prompt", null) != null:
		result.prompt = d["prompt"]
	return result
