@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelRaid
	


## 
## #/components/schemas/ChannelRaidCondition
class Condition extends TwitchData:

	## The broadcaster user ID that created the channel raid you want to get notifications for. Use this parameter if you want to know when a specific broadcaster raids another broadcaster. The channel raid condition must include either from_broadcaster_user_id or to_broadcaster_user_id.
	@export var from_broadcaster_user_id: String:
		set(val): 
			from_broadcaster_user_id = val
			track_data(&"from_broadcaster_user_id", val)
	
	## The broadcaster user ID that received the channel raid you want to get notifications for. Use this parameter if you want to know when a specific broadcaster is raided by another broadcaster. The channel raid condition must include either from_broadcaster_user_id or to_broadcaster_user_id.
	@export var to_broadcaster_user_id: String:
		set(val): 
			to_broadcaster_user_id = val
			track_data(&"to_broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("from_broadcaster_user_id", null) != null:
			result.from_broadcaster_user_id = d["from_broadcaster_user_id"]
		if d.get("to_broadcaster_user_id", null) != null:
			result.to_broadcaster_user_id = d["to_broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelRaidEvent
class Event extends TwitchData:

	## The broadcaster ID that created the raid.
	@export var from_broadcaster_user_id: String:
		set(val): 
			from_broadcaster_user_id = val
			track_data(&"from_broadcaster_user_id", val)
	
	## The broadcaster login that created the raid.
	@export var from_broadcaster_user_login: String:
		set(val): 
			from_broadcaster_user_login = val
			track_data(&"from_broadcaster_user_login", val)
	
	## The broadcaster display name that created the raid.
	@export var from_broadcaster_user_name: String:
		set(val): 
			from_broadcaster_user_name = val
			track_data(&"from_broadcaster_user_name", val)
	
	## The broadcaster ID that received the raid.
	@export var to_broadcaster_user_id: String:
		set(val): 
			to_broadcaster_user_id = val
			track_data(&"to_broadcaster_user_id", val)
	
	## The broadcaster login that received the raid.
	@export var to_broadcaster_user_login: String:
		set(val): 
			to_broadcaster_user_login = val
			track_data(&"to_broadcaster_user_login", val)
	
	## The broadcaster display name that received the raid.
	@export var to_broadcaster_user_name: String:
		set(val): 
			to_broadcaster_user_name = val
			track_data(&"to_broadcaster_user_name", val)
	
	## The number of viewers in the raid.
	@export var viewers: int:
		set(val): 
			viewers = val
			track_data(&"viewers", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("from_broadcaster_user_id", null) != null:
			result.from_broadcaster_user_id = d["from_broadcaster_user_id"]
		if d.get("from_broadcaster_user_login", null) != null:
			result.from_broadcaster_user_login = d["from_broadcaster_user_login"]
		if d.get("from_broadcaster_user_name", null) != null:
			result.from_broadcaster_user_name = d["from_broadcaster_user_name"]
		if d.get("to_broadcaster_user_id", null) != null:
			result.to_broadcaster_user_id = d["to_broadcaster_user_id"]
		if d.get("to_broadcaster_user_login", null) != null:
			result.to_broadcaster_user_login = d["to_broadcaster_user_login"]
		if d.get("to_broadcaster_user_name", null) != null:
			result.to_broadcaster_user_name = d["to_broadcaster_user_name"]
		if d.get("viewers", null) != null:
			result.viewers = d["viewers"]
		return result
	