@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESConduitShardDisabled
	


## 
## #/components/schemas/ConduitShardDisabledCondition
class Condition extends TwitchData:

	## Your application's client id. The provided client_id must match the client ID in the application access token.
	@export var client_id: String:
		set(val):
			client_id = val
			track_data(&"client_id", val)
	
	## The conduit ID to receive events for. If omitted, events for all of this client's conduits are sent.
	@export var conduit_id: String:
		set(val):
			conduit_id = val
			track_data(&"conduit_id", val)
	
	
	
	## Constructor with all required fields.
	static func create(_client_id: String) -> Condition:
		var condition: Condition = Condition.new()
		condition.client_id = _client_id
		return condition
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("client_id", null) != null:
			result.client_id = d["client_id"]
		if d.get("conduit_id", null) != null:
			result.conduit_id = d["conduit_id"]
		return result
	


## 
## #/components/schemas/ConduitShardDisabledEvent
class Event extends TwitchData:

	## The ID of the conduit.
	@export var conduit_id: String:
		set(val):
			conduit_id = val
			track_data(&"conduit_id", val)
	
	## The ID of the disabled shard.
	@export var shard_id: String:
		set(val):
			shard_id = val
			track_data(&"shard_id", val)
	
	## The new status of the transport.
	@export var status: String:
		set(val):
			status = val
			track_data(&"status", val)
	
	## The disabled transport.
	@export var transport: TwitchESTransport:
		set(val):
			transport = val
			track_data(&"transport", val)
	
	
	
	## Constructor with all required fields.
	static func create() -> Event:
		var event: Event = Event.new()
		return event
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("conduit_id", null) != null:
			result.conduit_id = d["conduit_id"]
		if d.get("shard_id", null) != null:
			result.shard_id = d["shard_id"]
		if d.get("status", null) != null:
			result.status = d["status"]
		if d.get("transport", null) != null:
			result.transport = TwitchESTransport.from_json(d["transport"])
		return result
	
