@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelPollEnd
	


## 
## #/components/schemas/ChannelPollEndCondition
class Condition extends TwitchData:

	## The broadcaster user ID of the channel for which “poll end” notifications will be received.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelPollEndEvent
class Event extends TwitchData:

	## ID of the poll.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## The requested broadcaster ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The requested broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The requested broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## Question displayed for the poll.
	@export var title: String:
		set(val): 
			title = val
			track_data(&"title", val)
	
	## An array of choices for the poll. Includes vote counts.
	@export var choices: Array[TwitchESChoices]:
		set(val): 
			choices = val
			track_data(&"choices", val)
	
	## Not supported.
	@export var bits_voting: TwitchESBitsVoting:
		set(val): 
			bits_voting = val
			track_data(&"bits_voting", val)
	
	## The Channel Points voting settings for the poll.
	@export var channel_points_voting: int:
		set(val): 
			channel_points_voting = val
			track_data(&"channel_points_voting", val)
	
	## The status of the poll. Valid values are completed, archived, and terminated.
	@export var status: String:
		set(val): 
			status = val
			track_data(&"status", val)
	
	## The time the poll started.
	@export var started_at: String:
		set(val): 
			started_at = val
			track_data(&"started_at", val)
	
	## The time the poll ended.
	@export var ended_at: String:
		set(val): 
			ended_at = val
			track_data(&"ended_at", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("title", null) != null:
			result.title = d["title"]
		if d.get("choices", null) != null:
			for value in d["choices"]:
				result.choices.append(TwitchESChoices.from_json(value))
		if d.get("bits_voting", null) != null:
			result.bits_voting = TwitchESBitsVoting.from_json(d["bits_voting"])
		if d.get("channel_points_voting", null) != null:
			result.channel_points_voting = d["channel_points_voting"]
		if d.get("status", null) != null:
			result.status = d["status"]
		if d.get("started_at", null) != null:
			result.started_at = d["started_at"]
		if d.get("ended_at", null) != null:
			result.ended_at = d["ended_at"]
		return result
	