@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelPointsCustomRewardRedemptionUpdate
	


## 
## #/components/schemas/ChannelPointsCustomRewardRedemptionUpdateCondition
class Condition extends TwitchData:

	## The broadcaster user ID for the channel you want to receive channel points custom reward redemption update notifications for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## Optional. Specify a reward id to only receive notifications for a specific reward.
	@export var reward_id: String:
		set(val): 
			reward_id = val
			track_data(&"reward_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("reward_id", null) != null:
			result.reward_id = d["reward_id"]
		return result
	


## 
## #/components/schemas/ChannelPointsCustomRewardRedemptionUpdateEvent
class Event extends TwitchData:

	## The redemption identifier.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## The requested broadcaster ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The requested broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The requested broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## User ID of the user that redeemed the reward.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## Login of the user that redeemed the reward.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## Display name of the user that redeemed the reward.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The user input provided. Empty string if not provided.
	@export var user_input: String:
		set(val): 
			user_input = val
			track_data(&"user_input", val)
	
	## Will be fulfilled or canceled. Possible values are unknown, unfulfilled, fulfilled, and canceled.
	@export var status: String:
		set(val): 
			status = val
			track_data(&"status", val)
	
	## Basic information about the reward that was redeemed, at the time it was redeemed.
	@export var reward: TwitchESReward:
		set(val): 
			reward = val
			track_data(&"reward", val)
	
	## RFC3339 timestamp of when the reward was redeemed.
	@export var redeemed_at: String:
		set(val): 
			redeemed_at = val
			track_data(&"redeemed_at", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("user_input", null) != null:
			result.user_input = d["user_input"]
		if d.get("status", null) != null:
			result.status = d["status"]
		if d.get("reward", null) != null:
			result.reward = TwitchESReward.from_json(d["reward"])
		if d.get("redeemed_at", null) != null:
			result.redeemed_at = d["redeemed_at"]
		return result
	