@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelChatNotification
	


## 
## #/components/schemas/ChannelChatNotificationCondition
class Condition extends TwitchData:

	## User ID of the channel to receive chat notification events for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The user ID to read chat as.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		return result
	


## 
## #/components/schemas/ChannelChatNotificationEvent
class Event extends TwitchData:

	## The broadcaster user ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The user ID of the user that sent the message.
	@export var chatter_user_id: String:
		set(val): 
			chatter_user_id = val
			track_data(&"chatter_user_id", val)
	
	## The user login of the user that sent the message.
	@export var chatter_user_name: String:
		set(val): 
			chatter_user_name = val
			track_data(&"chatter_user_name", val)
	
	## Whether or not the chatter is anonymous.
	@export var chatter_is_anonymous: bool:
		set(val): 
			chatter_is_anonymous = val
			track_data(&"chatter_is_anonymous", val)
	
	## The color of the user’s name in the chat room.
	@export var color: String:
		set(val): 
			color = val
			track_data(&"color", val)
	
	## The color of the user’s name in the chat room.
	@export var badges: Array[Badges]:
		set(val): 
			badges = val
			track_data(&"badges", val)
	
	## The message Twitch shows in the chat room for this notice.
	@export var system_message: String:
		set(val): 
			system_message = val
			track_data(&"system_message", val)
	
	## A UUID that identifies the message.
	@export var message_id: String:
		set(val): 
			message_id = val
			track_data(&"message_id", val)
	
	## The structured chat message.
	@export var message: Message:
		set(val): 
			message = val
			track_data(&"message", val)
	
	## The type of notice. Possible values are: subresubsub_giftcommunity_sub_giftgift_paid_upgradeprime_paid_upgraderaidunraidpay_it_forwardannouncementbits_badge_tiercharity_donationshared_chat_subshared_chat_resubshared_chat_sub_giftshared_chat_community_sub_giftshared_chat_gift_paid_upgradeshared_chat_prime_paid_upgradeshared_chat_raidshared_chat_pay_it_forwardshared_chat_announcement
	@export var notice_type: String:
		set(val): 
			notice_type = val
			track_data(&"notice_type", val)
	
	## Information about the sub event. Null if notice_type is not sub.
	@export var sub: Sub:
		set(val): 
			sub = val
			track_data(&"sub", val)
	
	## Information about the resub event. Null if notice_type is not resub.
	@export var resub: Resub:
		set(val): 
			resub = val
			track_data(&"resub", val)
	
	## Information about the gift sub event. Null if notice_type is not sub_gift.
	@export var sub_gift: SubGift:
		set(val): 
			sub_gift = val
			track_data(&"sub_gift", val)
	
	## Information about the community gift sub event. Null if notice_type is not community_sub_gift.
	@export var community_sub_gift: CommunitySubGift:
		set(val): 
			community_sub_gift = val
			track_data(&"community_sub_gift", val)
	
	## Information about the community gift paid upgrade event. Null if notice_type is not gift_paid_upgrade.
	@export var gift_paid_upgrade: GiftPaidUpgrade:
		set(val): 
			gift_paid_upgrade = val
			track_data(&"gift_paid_upgrade", val)
	
	## Information about the Prime gift paid upgrade event. Null if notice_type is not prime_paid_upgrade
	@export var prime_paid_upgrade: PrimePaidUpgrade:
		set(val): 
			prime_paid_upgrade = val
			track_data(&"prime_paid_upgrade", val)
	
	## Information about the pay it forward event. Null if notice_type is not pay_it_forward
	@export var pay_it_forward: PayItForward:
		set(val): 
			pay_it_forward = val
			track_data(&"pay_it_forward", val)
	
	## Information about the raid event. Null if notice_type is not raid
	@export var raid: Raid:
		set(val): 
			raid = val
			track_data(&"raid", val)
	
	## Returns an empty payload if notice_type is not unraid, otherwise returns null.
	@export var unraid: Dictionary:
		set(val): 
			unraid = val
			track_data(&"unraid", val)
	
	## Information about the announcement event. Null if notice_type is not {::nomarkdown}announcement
	@export var announcement: Announcement:
		set(val): 
			announcement = val
			track_data(&"announcement", val)
	
	## Information about the Bits badge tier event. Null if notice_type is not bits_badge_tier
	@export var bits_badge_tier: BitsBadgeTier:
		set(val): 
			bits_badge_tier = val
			track_data(&"bits_badge_tier", val)
	
	## Information about the announcement event. Null if notice_type is not charity_donation
	@export var charity_donation: CharityDonation:
		set(val): 
			charity_donation = val
			track_data(&"charity_donation", val)
	
	## Optional. The broadcaster user ID of the channel the message was sent from. Is null when the message notification happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_broadcaster_user_id: String:
		set(val): 
			source_broadcaster_user_id = val
			track_data(&"source_broadcaster_user_id", val)
	
	## Optional. The user name of the broadcaster of the channel the message was sent from. Is null when the message notification happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_broadcaster_user_name: String:
		set(val): 
			source_broadcaster_user_name = val
			track_data(&"source_broadcaster_user_name", val)
	
	## Optional. The login of the broadcaster of the channel the message was sent from. Is null when the message notification happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_broadcaster_user_login: String:
		set(val): 
			source_broadcaster_user_login = val
			track_data(&"source_broadcaster_user_login", val)
	
	## Optional. The UUID that identifies the source message from the channel the message was sent from. Is null when the message happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_message_id: String:
		set(val): 
			source_message_id = val
			track_data(&"source_message_id", val)
	
	## Optional. The list of chat badges for the chatter in the channel the message was sent from. Is null when the message happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_badges: SourceBadges:
		set(val): 
			source_badges = val
			track_data(&"source_badges", val)
	
	## Optional. Information about the shared_chat_sub event. Is null if notice_type is not shared_chat_sub. This field has the same information as the sub field but for a notice that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_sub: Dictionary:
		set(val): 
			shared_chat_sub = val
			track_data(&"shared_chat_sub", val)
	
	## Optional. Information about the shared_chat_resub event. Is null if notice_type is not shared_chat_resub. This field has the same information as the resub field but for a notice that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_resub: Dictionary:
		set(val): 
			shared_chat_resub = val
			track_data(&"shared_chat_resub", val)
	
	## Optional. Information about the shared_chat_sub_gift event. Is null if notice_type is not shared_chat_sub_gift. This field has the same information as the chat_sub_gift field but for a notice that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_sub_gift: Dictionary:
		set(val): 
			shared_chat_sub_gift = val
			track_data(&"shared_chat_sub_gift", val)
	
	## Optional. Information about the shared_chat_community_sub_gift event. Is null if notice_type is not shared_chat_community_sub_gift. This field has the same information as the community_sub_gift field but for a notice that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_community_sub_gift: Dictionary:
		set(val): 
			shared_chat_community_sub_gift = val
			track_data(&"shared_chat_community_sub_gift", val)
	
	## Optional. Information about the shared_chat_gift_paid_upgrade event. Is null if notice_type is not shared_chat_gift_paid_upgrade. This field has the same information as the gift_paid_upgrade field but for a notice that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_gift_paid_upgrade: Dictionary:
		set(val): 
			shared_chat_gift_paid_upgrade = val
			track_data(&"shared_chat_gift_paid_upgrade", val)
	
	## Optional. Information about the shared_chat_chat_prime_paid_upgrade event. Is null if notice_type is not shared_chat_prime_paid_upgrade. This field has the same information as the prime_paid_upgrade field but for a notice that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_prime_paid_upgrade: Dictionary:
		set(val): 
			shared_chat_prime_paid_upgrade = val
			track_data(&"shared_chat_prime_paid_upgrade", val)
	
	## Optional. Information about the shared_chat_pay_it_forward event. Is null if notice_type is not shared_chat_pay_it_forward. This field has the same information as the pay_it_forward field but for a notice that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_pay_it_forward: Dictionary:
		set(val): 
			shared_chat_pay_it_forward = val
			track_data(&"shared_chat_pay_it_forward", val)
	
	## Optional. Information about the shared_chat_raid event. Is null if notice_type is not shared_chat_raid. This field has the same information as the raid field but for a notice that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_raid: Dictionary:
		set(val): 
			shared_chat_raid = val
			track_data(&"shared_chat_raid", val)
	
	## Optional. Information about the shared_chat_announcement event. Is null if notice_type is not shared_chat_announcement. This field has the same information as the announcement field but for a notice that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_announcement: Dictionary:
		set(val): 
			shared_chat_announcement = val
			track_data(&"shared_chat_announcement", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("chatter_user_id", null) != null:
			result.chatter_user_id = d["chatter_user_id"]
		if d.get("chatter_user_name", null) != null:
			result.chatter_user_name = d["chatter_user_name"]
		if d.get("chatter_is_anonymous", null) != null:
			result.chatter_is_anonymous = d["chatter_is_anonymous"]
		if d.get("color", null) != null:
			result.color = d["color"]
		if d.get("badges", null) != null:
			for value in d["badges"]:
				result.badges.append(Badges.from_json(value))
		if d.get("system_message", null) != null:
			result.system_message = d["system_message"]
		if d.get("message_id", null) != null:
			result.message_id = d["message_id"]
		if d.get("message", null) != null:
			result.message = Message.from_json(d["message"])
		if d.get("notice_type", null) != null:
			result.notice_type = d["notice_type"]
		if d.get("sub", null) != null:
			result.sub = Sub.from_json(d["sub"])
		if d.get("resub", null) != null:
			result.resub = Resub.from_json(d["resub"])
		if d.get("sub_gift", null) != null:
			result.sub_gift = SubGift.from_json(d["sub_gift"])
		if d.get("community_sub_gift", null) != null:
			result.community_sub_gift = CommunitySubGift.from_json(d["community_sub_gift"])
		if d.get("gift_paid_upgrade", null) != null:
			result.gift_paid_upgrade = GiftPaidUpgrade.from_json(d["gift_paid_upgrade"])
		if d.get("prime_paid_upgrade", null) != null:
			result.prime_paid_upgrade = PrimePaidUpgrade.from_json(d["prime_paid_upgrade"])
		if d.get("pay_it_forward", null) != null:
			result.pay_it_forward = PayItForward.from_json(d["pay_it_forward"])
		if d.get("raid", null) != null:
			result.raid = Raid.from_json(d["raid"])
		if d.get("unraid", null) != null:
			result.unraid = d["unraid"]
		if d.get("announcement", null) != null:
			result.announcement = Announcement.from_json(d["announcement"])
		if d.get("bits_badge_tier", null) != null:
			result.bits_badge_tier = BitsBadgeTier.from_json(d["bits_badge_tier"])
		if d.get("charity_donation", null) != null:
			result.charity_donation = CharityDonation.from_json(d["charity_donation"])
		if d.get("source_broadcaster_user_id", null) != null:
			result.source_broadcaster_user_id = d["source_broadcaster_user_id"]
		if d.get("source_broadcaster_user_name", null) != null:
			result.source_broadcaster_user_name = d["source_broadcaster_user_name"]
		if d.get("source_broadcaster_user_login", null) != null:
			result.source_broadcaster_user_login = d["source_broadcaster_user_login"]
		if d.get("source_message_id", null) != null:
			result.source_message_id = d["source_message_id"]
		if d.get("source_badges", null) != null:
			result.source_badges = SourceBadges.from_json(d["source_badges"])
		if d.get("shared_chat_sub", null) != null:
			result.shared_chat_sub = d["shared_chat_sub"]
		if d.get("shared_chat_resub", null) != null:
			result.shared_chat_resub = d["shared_chat_resub"]
		if d.get("shared_chat_sub_gift", null) != null:
			result.shared_chat_sub_gift = d["shared_chat_sub_gift"]
		if d.get("shared_chat_community_sub_gift", null) != null:
			result.shared_chat_community_sub_gift = d["shared_chat_community_sub_gift"]
		if d.get("shared_chat_gift_paid_upgrade", null) != null:
			result.shared_chat_gift_paid_upgrade = d["shared_chat_gift_paid_upgrade"]
		if d.get("shared_chat_prime_paid_upgrade", null) != null:
			result.shared_chat_prime_paid_upgrade = d["shared_chat_prime_paid_upgrade"]
		if d.get("shared_chat_pay_it_forward", null) != null:
			result.shared_chat_pay_it_forward = d["shared_chat_pay_it_forward"]
		if d.get("shared_chat_raid", null) != null:
			result.shared_chat_raid = d["shared_chat_raid"]
		if d.get("shared_chat_announcement", null) != null:
			result.shared_chat_announcement = d["shared_chat_announcement"]
		return result
	


## The color of the user’s name in the chat room.
## #/components/schemas/ChannelChatNotificationEvent/Badges
class Badges extends TwitchData:

	## An ID that identifies this set of chat badges. For example, Bits or Subscriber.
	@export var set_id: String:
		set(val): 
			set_id = val
			track_data(&"set_id", val)
	
	## An ID that identifies this version of the badge. The ID can be any value. For example, for Bits, the ID is the Bits tier level, but for World of Warcraft, it could be Alliance or Horde.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## Contains metadata related to the chat badges in the badges tag. Currently, this tag contains metadata only for subscriber badges, to indicate the number of months the user has been a subscriber.
	@export var info: String:
		set(val): 
			info = val
			track_data(&"info", val)
	
	
	
	static func from_json(d: Dictionary) -> Badges:
		var result: Badges = Badges.new()
		if d.get("set_id", null) != null:
			result.set_id = d["set_id"]
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("info", null) != null:
			result.info = d["info"]
		return result
	


## The structured chat message.
## #/components/schemas/ChannelChatNotificationEvent/Message
class Message extends TwitchData:

	## The chat message in plain text.
	@export var text: Dictionary:
		set(val): 
			text = val
			track_data(&"text", val)
	
	## Ordered list of chat message fragments.
	@export var fragments: Array[Fragments]:
		set(val): 
			fragments = val
			track_data(&"fragments", val)
	
	
	
	static func from_json(d: Dictionary) -> Message:
		var result: Message = Message.new()
		if d.get("text", null) != null:
			result.text = d["text"]
		if d.get("fragments", null) != null:
			for value in d["fragments"]:
				result.fragments.append(Fragments.from_json(value))
		return result
	


## Ordered list of chat message fragments.
## #/components/schemas/ChannelChatNotificationEvent/Message/Fragments
class Fragments extends TwitchData:

	## The type of message fragment. Possible values: textcheermoteemotemention
	@export var type: String:
		set(val): 
			type = val
			track_data(&"type", val)
	
	## Message text in fragment.
	@export var text: String:
		set(val): 
			text = val
			track_data(&"text", val)
	
	## Optional. Metadata pertaining to the cheermote.
	@export var cheermote: Cheermote:
		set(val): 
			cheermote = val
			track_data(&"cheermote", val)
	
	## Optional. Metadata pertaining to the emote.
	@export var emote: Emote:
		set(val): 
			emote = val
			track_data(&"emote", val)
	
	## Optional. Metadata pertaining to the mention.
	@export var mention: Mention:
		set(val): 
			mention = val
			track_data(&"mention", val)
	
	
	
	static func from_json(d: Dictionary) -> Fragments:
		var result: Fragments = Fragments.new()
		if d.get("type", null) != null:
			result.type = d["type"]
		if d.get("text", null) != null:
			result.text = d["text"]
		if d.get("cheermote", null) != null:
			result.cheermote = Cheermote.from_json(d["cheermote"])
		if d.get("emote", null) != null:
			result.emote = Emote.from_json(d["emote"])
		if d.get("mention", null) != null:
			result.mention = Mention.from_json(d["mention"])
		return result
	


## Optional. Metadata pertaining to the cheermote.
## #/components/schemas/ChannelChatNotificationEvent/Message/Fragments/Cheermote
class Cheermote extends TwitchData:

	## The name portion of the Cheermote string that you use in chat to cheer Bits. The full Cheermote string is the concatenation of {prefix} + {number of Bits}. For example, if the prefix is “Cheer” and you want to cheer 100 Bits, the full Cheermote string is Cheer100. When the Cheermote string is entered in chat, Twitch converts it to the image associated with the Bits tier that was cheered.
	@export var prefix: Dictionary:
		set(val): 
			prefix = val
			track_data(&"prefix", val)
	
	## The amount of Bits cheered.
	@export var bits: int:
		set(val): 
			bits = val
			track_data(&"bits", val)
	
	## The tier level of the cheermote.
	@export var tier: int:
		set(val): 
			tier = val
			track_data(&"tier", val)
	
	
	
	static func from_json(d: Dictionary) -> Cheermote:
		var result: Cheermote = Cheermote.new()
		if d.get("prefix", null) != null:
			result.prefix = d["prefix"]
		if d.get("bits", null) != null:
			result.bits = d["bits"]
		if d.get("tier", null) != null:
			result.tier = d["tier"]
		return result
	


## Optional. Metadata pertaining to the emote.
## #/components/schemas/ChannelChatNotificationEvent/Message/Fragments/Emote
class Emote extends TwitchData:

	## An ID that uniquely identifies this emote.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## An ID that identifies the emote set that the emote belongs to.
	@export var emote_set_id: String:
		set(val): 
			emote_set_id = val
			track_data(&"emote_set_id", val)
	
	## The ID of the broadcaster who owns the emote.
	@export var owner_id: String:
		set(val): 
			owner_id = val
			track_data(&"owner_id", val)
	
	## The formats that the emote is available in. For example, if the emote is available only as a static PNG, the array contains only static. But if the emote is available as a static PNG and an animated GIF, the array contains static and animated. The possible formats are: animated - An animated GIF is available for this emote.static - A static PNG file is available for this emote.
	@export var format: Array[String]:
		set(val): 
			format = val
			track_data(&"format", val)
	
	
	
	static func from_json(d: Dictionary) -> Emote:
		var result: Emote = Emote.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("emote_set_id", null) != null:
			result.emote_set_id = d["emote_set_id"]
		if d.get("owner_id", null) != null:
			result.owner_id = d["owner_id"]
		if d.get("format", null) != null:
			for value in d["format"]:
				result.format.append(value)
		return result
	


## Optional. Metadata pertaining to the mention.
## #/components/schemas/ChannelChatNotificationEvent/Message/Fragments/Mention
class Mention extends TwitchData:

	## The user ID of the mentioned user.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The user name of the mentioned user.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The user login of the mentioned user.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	
	
	static func from_json(d: Dictionary) -> Mention:
		var result: Mention = Mention.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		return result
	


## Information about the sub event. Null if notice_type is not sub.
## #/components/schemas/ChannelChatNotificationEvent/Sub
class Sub extends TwitchData:

	## The type of subscription plan being used. Possible values are: 1000 - First level of paid or Prime subscription.2000 - Second level of paid subscription.3000 - Third level of paid subscription.
	@export var sub_tier: String:
		set(val): 
			sub_tier = val
			track_data(&"sub_tier", val)
	
	## Indicates if the subscription was obtained through Amazon Prime.
	@export var is_prime: bool:
		set(val): 
			is_prime = val
			track_data(&"is_prime", val)
	
	## The number of months the subscription is for.
	@export var duration_months: int:
		set(val): 
			duration_months = val
			track_data(&"duration_months", val)
	
	
	
	static func from_json(d: Dictionary) -> Sub:
		var result: Sub = Sub.new()
		if d.get("sub_tier", null) != null:
			result.sub_tier = d["sub_tier"]
		if d.get("is_prime", null) != null:
			result.is_prime = d["is_prime"]
		if d.get("duration_months", null) != null:
			result.duration_months = d["duration_months"]
		return result
	


## Information about the resub event. Null if notice_type is not resub.
## #/components/schemas/ChannelChatNotificationEvent/Resub
class Resub extends TwitchData:

	## The total number of months the user has subscribed.
	@export var cumulative_months: int:
		set(val): 
			cumulative_months = val
			track_data(&"cumulative_months", val)
	
	## The number of months the subscription is for.
	@export var duration_months: int:
		set(val): 
			duration_months = val
			track_data(&"duration_months", val)
	
	## The total number of months the user has subscribed.
	@export var streak_months: int:
		set(val): 
			streak_months = val
			track_data(&"streak_months", val)
	
	## The type of subscription plan being used. Possible values are: 1000 - First level of paid or Prime subscription.2000 - Second level of paid subscription.3000 - Third level of paid subscription.
	@export var sub_tier: String:
		set(val): 
			sub_tier = val
			track_data(&"sub_tier", val)
	
	## Optional. The number of consecutive months the user has subscribed.
	@export var is_prime: bool:
		set(val): 
			is_prime = val
			track_data(&"is_prime", val)
	
	## Whether or not the resub was a result of a gift.
	@export var is_gift: bool:
		set(val): 
			is_gift = val
			track_data(&"is_gift", val)
	
	## Optional. Whether or not the gift was anonymous.
	@export var gifter_is_anonymous: bool:
		set(val): 
			gifter_is_anonymous = val
			track_data(&"gifter_is_anonymous", val)
	
	## The user ID of the subscription gifter. Null if anonymous.
	@export var gifter_user_id: String:
		set(val): 
			gifter_user_id = val
			track_data(&"gifter_user_id", val)
	
	## The user name of the subscription gifter. Null if anonymous.
	@export var gifter_user_name: String:
		set(val): 
			gifter_user_name = val
			track_data(&"gifter_user_name", val)
	
	## Optional. The user login of the subscription gifter. Null if anonymous.
	@export var gifter_user_login: String:
		set(val): 
			gifter_user_login = val
			track_data(&"gifter_user_login", val)
	
	
	
	static func from_json(d: Dictionary) -> Resub:
		var result: Resub = Resub.new()
		if d.get("cumulative_months", null) != null:
			result.cumulative_months = d["cumulative_months"]
		if d.get("duration_months", null) != null:
			result.duration_months = d["duration_months"]
		if d.get("streak_months", null) != null:
			result.streak_months = d["streak_months"]
		if d.get("sub_tier", null) != null:
			result.sub_tier = d["sub_tier"]
		if d.get("is_prime", null) != null:
			result.is_prime = d["is_prime"]
		if d.get("is_gift", null) != null:
			result.is_gift = d["is_gift"]
		if d.get("gifter_is_anonymous", null) != null:
			result.gifter_is_anonymous = d["gifter_is_anonymous"]
		if d.get("gifter_user_id", null) != null:
			result.gifter_user_id = d["gifter_user_id"]
		if d.get("gifter_user_name", null) != null:
			result.gifter_user_name = d["gifter_user_name"]
		if d.get("gifter_user_login", null) != null:
			result.gifter_user_login = d["gifter_user_login"]
		return result
	


## Information about the gift sub event. Null if notice_type is not sub_gift.
## #/components/schemas/ChannelChatNotificationEvent/SubGift
class SubGift extends TwitchData:

	## The number of months the subscription is for.
	@export var duration_months: int:
		set(val): 
			duration_months = val
			track_data(&"duration_months", val)
	
	## Optional. The amount of gifts the gifter has given in this channel. Null if anonymous.
	@export var cumulative_total: int:
		set(val): 
			cumulative_total = val
			track_data(&"cumulative_total", val)
	
	## The user ID of the subscription gift recipient.
	@export var recipient_user_id: String:
		set(val): 
			recipient_user_id = val
			track_data(&"recipient_user_id", val)
	
	## The user name of the subscription gift recipient.
	@export var recipient_user_name: String:
		set(val): 
			recipient_user_name = val
			track_data(&"recipient_user_name", val)
	
	## The user login of the subscription gift recipient.
	@export var recipient_user_login: String:
		set(val): 
			recipient_user_login = val
			track_data(&"recipient_user_login", val)
	
	## The type of subscription plan being used. Possible values are: 1000 - First level of paid or Prime subscription.2000 - Second level of paid subscription.3000 - Third level of paid subscription.
	@export var sub_tier: String:
		set(val): 
			sub_tier = val
			track_data(&"sub_tier", val)
	
	## Optional. The ID of the associated community gift. Null if not associated with a community gift.
	@export var community_gift_id: String:
		set(val): 
			community_gift_id = val
			track_data(&"community_gift_id", val)
	
	
	
	static func from_json(d: Dictionary) -> SubGift:
		var result: SubGift = SubGift.new()
		if d.get("duration_months", null) != null:
			result.duration_months = d["duration_months"]
		if d.get("cumulative_total", null) != null:
			result.cumulative_total = d["cumulative_total"]
		if d.get("recipient_user_id", null) != null:
			result.recipient_user_id = d["recipient_user_id"]
		if d.get("recipient_user_name", null) != null:
			result.recipient_user_name = d["recipient_user_name"]
		if d.get("recipient_user_login", null) != null:
			result.recipient_user_login = d["recipient_user_login"]
		if d.get("sub_tier", null) != null:
			result.sub_tier = d["sub_tier"]
		if d.get("community_gift_id", null) != null:
			result.community_gift_id = d["community_gift_id"]
		return result
	


## Information about the community gift sub event. Null if notice_type is not community_sub_gift.
## #/components/schemas/ChannelChatNotificationEvent/CommunitySubGift
class CommunitySubGift extends TwitchData:

	## The ID of the associated community gift.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## Number of subscriptions being gifted.
	@export var total: int:
		set(val): 
			total = val
			track_data(&"total", val)
	
	## The type of subscription plan being used. Possible values are: <ul><li>1000 - First level of paid or Prime subscription.</li><li>2000 - Second level of paid subscription.</li><li>3000 - Third level of paid subscription.</li></ul>
	@export var sub_tier: String:
		set(val): 
			sub_tier = val
			track_data(&"sub_tier", val)
	
	## Optional. The amount of gifts the gifter has given in this channel. Null if anonymous.
	@export var cumulative_total: int:
		set(val): 
			cumulative_total = val
			track_data(&"cumulative_total", val)
	
	
	
	static func from_json(d: Dictionary) -> CommunitySubGift:
		var result: CommunitySubGift = CommunitySubGift.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("total", null) != null:
			result.total = d["total"]
		if d.get("sub_tier", null) != null:
			result.sub_tier = d["sub_tier"]
		if d.get("cumulative_total", null) != null:
			result.cumulative_total = d["cumulative_total"]
		return result
	


## Information about the community gift paid upgrade event. Null if notice_type is not gift_paid_upgrade.
## #/components/schemas/ChannelChatNotificationEvent/GiftPaidUpgrade
class GiftPaidUpgrade extends TwitchData:

	## Whether the gift was given anonymously.
	@export var gifter_is_anonymous: bool:
		set(val): 
			gifter_is_anonymous = val
			track_data(&"gifter_is_anonymous", val)
	
	## Optional. The user ID of the user who gifted the subscription. Null if anonymous.
	@export var gifter_user_id: String:
		set(val): 
			gifter_user_id = val
			track_data(&"gifter_user_id", val)
	
	## Optional. The user name of the user who gifted the subscription. Null if anonymous.
	@export var gifter_user_name: String:
		set(val): 
			gifter_user_name = val
			track_data(&"gifter_user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> GiftPaidUpgrade:
		var result: GiftPaidUpgrade = GiftPaidUpgrade.new()
		if d.get("gifter_is_anonymous", null) != null:
			result.gifter_is_anonymous = d["gifter_is_anonymous"]
		if d.get("gifter_user_id", null) != null:
			result.gifter_user_id = d["gifter_user_id"]
		if d.get("gifter_user_name", null) != null:
			result.gifter_user_name = d["gifter_user_name"]
		return result
	


## Information about the Prime gift paid upgrade event. Null if notice_type is not prime_paid_upgrade
## #/components/schemas/ChannelChatNotificationEvent/PrimePaidUpgrade
class PrimePaidUpgrade extends TwitchData:

	## The type of subscription plan being used. Possible values are: 1000 - First level of paid or Prime subscription.2000 - Second level of paid subscription.3000 - Third level of paid subscription.
	@export var sub_tier: String:
		set(val): 
			sub_tier = val
			track_data(&"sub_tier", val)
	
	
	
	static func from_json(d: Dictionary) -> PrimePaidUpgrade:
		var result: PrimePaidUpgrade = PrimePaidUpgrade.new()
		if d.get("sub_tier", null) != null:
			result.sub_tier = d["sub_tier"]
		return result
	


## Information about the pay it forward event. Null if notice_type is not pay_it_forward
## #/components/schemas/ChannelChatNotificationEvent/PayItForward
class PayItForward extends TwitchData:

	## Whether the gift was given anonymously.
	@export var gifter_is_anonymous: bool:
		set(val): 
			gifter_is_anonymous = val
			track_data(&"gifter_is_anonymous", val)
	
	## The user ID of the user who gifted the subscription. Null if anonymous.
	@export var gifter_user_id: String:
		set(val): 
			gifter_user_id = val
			track_data(&"gifter_user_id", val)
	
	## Optional. The user name of the user who gifted the subscription. Null if anonymous.
	@export var gifter_user_name: String:
		set(val): 
			gifter_user_name = val
			track_data(&"gifter_user_name", val)
	
	## The user login of the user who gifted the subscription. Null if anonymous.
	@export var gifter_user_login: String:
		set(val): 
			gifter_user_login = val
			track_data(&"gifter_user_login", val)
	
	
	
	static func from_json(d: Dictionary) -> PayItForward:
		var result: PayItForward = PayItForward.new()
		if d.get("gifter_is_anonymous", null) != null:
			result.gifter_is_anonymous = d["gifter_is_anonymous"]
		if d.get("gifter_user_id", null) != null:
			result.gifter_user_id = d["gifter_user_id"]
		if d.get("gifter_user_name", null) != null:
			result.gifter_user_name = d["gifter_user_name"]
		if d.get("gifter_user_login", null) != null:
			result.gifter_user_login = d["gifter_user_login"]
		return result
	


## Information about the raid event. Null if notice_type is not raid
## #/components/schemas/ChannelChatNotificationEvent/Raid
class Raid extends TwitchData:

	## The user ID of the broadcaster raiding this channel.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The user name of the broadcaster raiding this channel.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The login name of the broadcaster raiding this channel.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The number of viewers raiding this channel from the broadcaster’s channel.
	@export var viewer_count: int:
		set(val): 
			viewer_count = val
			track_data(&"viewer_count", val)
	
	## Profile image URL of the broadcaster raiding this channel.
	@export var profile_image_url: String:
		set(val): 
			profile_image_url = val
			track_data(&"profile_image_url", val)
	
	
	
	static func from_json(d: Dictionary) -> Raid:
		var result: Raid = Raid.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("viewer_count", null) != null:
			result.viewer_count = d["viewer_count"]
		if d.get("profile_image_url", null) != null:
			result.profile_image_url = d["profile_image_url"]
		return result
	


## Information about the announcement event. Null if notice_type is not {::nomarkdown}announcement
## #/components/schemas/ChannelChatNotificationEvent/Announcement
class Announcement extends TwitchData:

	## Color of the announcement.
	@export var color: String:
		set(val): 
			color = val
			track_data(&"color", val)
	
	
	
	static func from_json(d: Dictionary) -> Announcement:
		var result: Announcement = Announcement.new()
		if d.get("color", null) != null:
			result.color = d["color"]
		return result
	


## Information about the Bits badge tier event. Null if notice_type is not bits_badge_tier
## #/components/schemas/ChannelChatNotificationEvent/BitsBadgeTier
class BitsBadgeTier extends TwitchData:

	## The tier of the Bits badge the user just earned. For example, 100, 1000, or 10000.
	@export var tier: int:
		set(val): 
			tier = val
			track_data(&"tier", val)
	
	
	
	static func from_json(d: Dictionary) -> BitsBadgeTier:
		var result: BitsBadgeTier = BitsBadgeTier.new()
		if d.get("tier", null) != null:
			result.tier = d["tier"]
		return result
	


## Information about the announcement event. Null if notice_type is not charity_donation
## #/components/schemas/ChannelChatNotificationEvent/CharityDonation
class CharityDonation extends TwitchData:

	## Name of the charity.
	@export var charity_name: String:
		set(val): 
			charity_name = val
			track_data(&"charity_name", val)
	
	## An object that contains the amount of money that the user paid.
	@export var amount: Amount:
		set(val): 
			amount = val
			track_data(&"amount", val)
	
	
	
	static func from_json(d: Dictionary) -> CharityDonation:
		var result: CharityDonation = CharityDonation.new()
		if d.get("charity_name", null) != null:
			result.charity_name = d["charity_name"]
		if d.get("amount", null) != null:
			result.amount = Amount.from_json(d["amount"])
		return result
	


## An object that contains the amount of money that the user paid.
## #/components/schemas/ChannelChatNotificationEvent/CharityDonation/Amount
class Amount extends TwitchData:

	## The monetary amount. The amount is specified in the currency’s minor unit. For example, the minor units for USD is cents, so if the amount is $5.50 USD, value is set to 550.
	@export var value: int:
		set(val): 
			value = val
			track_data(&"value", val)
	
	## The number of decimal places used by the currency. For example, USD uses two decimal places.
	@export var decimal_place: int:
		set(val): 
			decimal_place = val
			track_data(&"decimal_place", val)
	
	## The ISO-4217 three-letter currency code that identifies the type of currency in value.
	@export var currency: String:
		set(val): 
			currency = val
			track_data(&"currency", val)
	
	
	
	static func from_json(d: Dictionary) -> Amount:
		var result: Amount = Amount.new()
		if d.get("value", null) != null:
			result.value = d["value"]
		if d.get("decimal_place", null) != null:
			result.decimal_place = d["decimal_place"]
		if d.get("currency", null) != null:
			result.currency = d["currency"]
		return result
	


## Optional. The list of chat badges for the chatter in the channel the message was sent from. Is null when the message happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
## #/components/schemas/ChannelChatNotificationEvent/SourceBadges
class SourceBadges extends TwitchData:

	## The ID that identifies this set of chat badges. For example, Bits or Subscriber.
	@export var set_id: String:
		set(val): 
			set_id = val
			track_data(&"set_id", val)
	
	## The ID that identifies this version of the badge. The ID can be any value. For example, for Bits, the ID is the Bits tier level, but for World of Warcraft, it could be Alliance or Horde.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## Contains metadata related to the chat badges in the badges tag. Currently, this tag contains metadata only for subscriber badges, to indicate the number of months the user has been a subscriber.
	@export var info: String:
		set(val): 
			info = val
			track_data(&"info", val)
	
	
	
	static func from_json(d: Dictionary) -> SourceBadges:
		var result: SourceBadges = SourceBadges.new()
		if d.get("set_id", null) != null:
			result.set_id = d["set_id"]
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("info", null) != null:
			result.info = d["info"]
		return result
	