@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/TopPredictors
class_name TwitchESTopPredictors
	
## The ID of the user.
@export var user_id: String:
	set(val): 
		user_id = val
		track_data(&"user_id", val)

## The login of the user.
@export var user_login: String:
	set(val): 
		user_login = val
		track_data(&"user_login", val)

## The display name of the user.
@export var user_name: String:
	set(val): 
		user_name = val
		track_data(&"user_name", val)

## The number of Channel Points won. This value is always null in the event payload for Prediction progress and Prediction lock. This value is 0 if the outcome did not win or if the Prediction was canceled and Channel Points were refunded.
@export var channel_points_won: int:
	set(val): 
		channel_points_won = val
		track_data(&"channel_points_won", val)

## The number of Channel Points used to participate in the Prediction.
@export var channel_points_used: int:
	set(val): 
		channel_points_used = val
		track_data(&"channel_points_used", val)



static func from_json(d: Dictionary) -> TwitchESTopPredictors:
	var result: TwitchESTopPredictors = TwitchESTopPredictors.new()
	if d.get("user_id", null) != null:
		result.user_id = d["user_id"]
	if d.get("user_login", null) != null:
		result.user_login = d["user_login"]
	if d.get("user_name", null) != null:
		result.user_name = d["user_name"]
	if d.get("channel_points_won", null) != null:
		result.channel_points_won = d["channel_points_won"]
	if d.get("channel_points_used", null) != null:
		result.channel_points_used = d["channel_points_used"]
	return result
