@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/ShieldMode
class_name TwitchESShieldMode
	
## An ID that identifies the broadcaster whose Shield Mode status was updated.
@export var broadcaster_user_id: String:
	set(val): 
		broadcaster_user_id = val
		track_data(&"broadcaster_user_id", val)

## The broadcaster’s login name.
@export var broadcaster_user_login: String:
	set(val): 
		broadcaster_user_login = val
		track_data(&"broadcaster_user_login", val)

## The broadcaster’s display name.
@export var broadcaster_user_name: String:
	set(val): 
		broadcaster_user_name = val
		track_data(&"broadcaster_user_name", val)

## An ID that identifies the moderator that updated the Shield Mode’s status. If the broadcaster updated the status, this ID will be the same as broadcaster_user_id.
@export var moderator_user_id: String:
	set(val): 
		moderator_user_id = val
		track_data(&"moderator_user_id", val)

## The moderator’s login name.
@export var moderator_user_login: String:
	set(val): 
		moderator_user_login = val
		track_data(&"moderator_user_login", val)

## The moderator’s display name.
@export var moderator_user_name: String:
	set(val): 
		moderator_user_name = val
		track_data(&"moderator_user_name", val)

## The UTC timestamp (in RFC3339 format) of when the moderator activated Shield Mode. The object includes this field only for channel.shield_mode.begin events.
@export var started_at: String:
	set(val): 
		started_at = val
		track_data(&"started_at", val)

## The UTC timestamp (in RFC3339 format) of when the moderator deactivated Shield Mode. The object includes this field only for channel.shield_mode.end events.
@export var ended_at: String:
	set(val): 
		ended_at = val
		track_data(&"ended_at", val)



static func from_json(d: Dictionary) -> TwitchESShieldMode:
	var result: TwitchESShieldMode = TwitchESShieldMode.new()
	if d.get("broadcaster_user_id", null) != null:
		result.broadcaster_user_id = d["broadcaster_user_id"]
	if d.get("broadcaster_user_login", null) != null:
		result.broadcaster_user_login = d["broadcaster_user_login"]
	if d.get("broadcaster_user_name", null) != null:
		result.broadcaster_user_name = d["broadcaster_user_name"]
	if d.get("moderator_user_id", null) != null:
		result.moderator_user_id = d["moderator_user_id"]
	if d.get("moderator_user_login", null) != null:
		result.moderator_user_login = d["moderator_user_login"]
	if d.get("moderator_user_name", null) != null:
		result.moderator_user_name = d["moderator_user_name"]
	if d.get("started_at", null) != null:
		result.started_at = d["started_at"]
	if d.get("ended_at", null) != null:
		result.ended_at = d["ended_at"]
	return result
