@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelModerate
	


## 
## #/components/schemas/ChannelModerateCondition
class Condition extends TwitchData:

	## The user ID of the broadcaster.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The user ID of the moderator.
	@export var moderator_user_id: String:
		set(val): 
			moderator_user_id = val
			track_data(&"moderator_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("moderator_user_id", null) != null:
			result.moderator_user_id = d["moderator_user_id"]
		return result
	


## 
## #/components/schemas/ChannelModerateEvent
class Event extends TwitchData:

	## The ID of the broadcaster.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The login of the broadcaster.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The user name of the broadcaster.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The channel in which the action originally occurred. Is the same as the broadcaster_user_id if not in shared chat.
	@export var source_broadcaster_user_id: String:
		set(val): 
			source_broadcaster_user_id = val
			track_data(&"source_broadcaster_user_id", val)
	
	## The channel in which the action originally occurred. Is the same as the broadcaster_user_login if not in shared chat.
	@export var source_broadcaster_user_login: String:
		set(val): 
			source_broadcaster_user_login = val
			track_data(&"source_broadcaster_user_login", val)
	
	## The channel in which the action originally occurred. Is null when the moderator action happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_broadcaster_user_name: String:
		set(val): 
			source_broadcaster_user_name = val
			track_data(&"source_broadcaster_user_name", val)
	
	## The ID of the moderator who performed the action.
	@export var moderator_user_id: String:
		set(val): 
			moderator_user_id = val
			track_data(&"moderator_user_id", val)
	
	## The login of the moderator.
	@export var moderator_user_login: String:
		set(val): 
			moderator_user_login = val
			track_data(&"moderator_user_login", val)
	
	## The user name of the moderator.
	@export var moderator_user_name: String:
		set(val): 
			moderator_user_name = val
			track_data(&"moderator_user_name", val)
	
	## The type of action: Possible values are: bantimeoutunbanuntimeoutclearemoteonlyemoteonlyofffollowersfollowersoffuniquechatuniquechatoffslowslowoffsubscriberssubscribersoffunraiddeleteunvipvipraidadd_blocked_termadd_permitted_termremove_blocked_termremove_permitted_termmodunmodapprove_unban_requestdeny_unban_requestshared_chat_banshared_chat_timeoutshared_chat_untimeoutshared_chat_unbanshared_chat_delete
	@export var action: String:
		set(val): 
			action = val
			track_data(&"action", val)
	
	## Optional.. Metadata associated with the followers command.
	@export var followers: Followers:
		set(val): 
			followers = val
			track_data(&"followers", val)
	
	## Optional. Metadata associated with the slow command.
	@export var slow: Slow:
		set(val): 
			slow = val
			track_data(&"slow", val)
	
	## Optional. Metadata associated with the vip command.
	@export var vip: Vip:
		set(val): 
			vip = val
			track_data(&"vip", val)
	
	## Optional. Metadata associated with the unvip command.
	@export var unvip: Unvip:
		set(val): 
			unvip = val
			track_data(&"unvip", val)
	
	## Optional. Metadata associated with the mod command.
	@export var mod: Mod:
		set(val): 
			mod = val
			track_data(&"mod", val)
	
	## Optional. Metadata associated with the unmod command.
	@export var unmod: Unmod:
		set(val): 
			unmod = val
			track_data(&"unmod", val)
	
	## Optional. Metadata associated with the ban command.
	@export var ban: Ban:
		set(val): 
			ban = val
			track_data(&"ban", val)
	
	## Optional. Metadata associated with the unban command.
	@export var unban: Unban:
		set(val): 
			unban = val
			track_data(&"unban", val)
	
	## Optional.. Metadata associated with the timeout command.
	@export var timeout: Timeout:
		set(val): 
			timeout = val
			track_data(&"timeout", val)
	
	## Optional. Metadata associated with the untimeout command.
	@export var untimeout: Untimeout:
		set(val): 
			untimeout = val
			track_data(&"untimeout", val)
	
	## Optional.. Metadata associated with the raid command.
	@export var raid: Raid:
		set(val): 
			raid = val
			track_data(&"raid", val)
	
	## Optional. Metadata associated with the unraid command.
	@export var unraid: Unraid:
		set(val): 
			unraid = val
			track_data(&"unraid", val)
	
	## Optional. Metadata associated with the delete command.
	@export var delete: Delete:
		set(val): 
			delete = val
			track_data(&"delete", val)
	
	## Optional. Metadata associated with the automod terms changes.
	@export var automod_terms: AutomodTerms:
		set(val): 
			automod_terms = val
			track_data(&"automod_terms", val)
	
	## Optional. Metadata associated with an unban request.
	@export var unban_request: UnbanRequest:
		set(val): 
			unban_request = val
			track_data(&"unban_request", val)
	
	## Optional. Information about the shared_chat_ban event. Is null if action is not shared_chat_ban. This field has the same information as the ban field but for a action that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_ban: Dictionary:
		set(val): 
			shared_chat_ban = val
			track_data(&"shared_chat_ban", val)
	
	## Optional. Information about the shared_chat_unban event. Is null if action is not shared_chat_unban. This field has the same information as the unban field but for a action that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_unban: Dictionary:
		set(val): 
			shared_chat_unban = val
			track_data(&"shared_chat_unban", val)
	
	## Optional. Information about the shared_chat_timeout event. Is null if action is not shared_chat_timeout. This field has the same information as the timeout field but for a action that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_timeout: Dictionary:
		set(val): 
			shared_chat_timeout = val
			track_data(&"shared_chat_timeout", val)
	
	## Optional. Information about the shared_chat_untimeout event. Is null if action is not shared_chat_untimeout. This field has the same information as the untimeout field but for a action that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_untimeout: Dictionary:
		set(val): 
			shared_chat_untimeout = val
			track_data(&"shared_chat_untimeout", val)
	
	## Optional. Information about the shared_chat_delete event. Is null if action is not shared_chat_delete. This field has the same information as the delete field but for a action that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_delete: Dictionary:
		set(val): 
			shared_chat_delete = val
			track_data(&"shared_chat_delete", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("source_broadcaster_user_id", null) != null:
			result.source_broadcaster_user_id = d["source_broadcaster_user_id"]
		if d.get("source_broadcaster_user_login", null) != null:
			result.source_broadcaster_user_login = d["source_broadcaster_user_login"]
		if d.get("source_broadcaster_user_name", null) != null:
			result.source_broadcaster_user_name = d["source_broadcaster_user_name"]
		if d.get("moderator_user_id", null) != null:
			result.moderator_user_id = d["moderator_user_id"]
		if d.get("moderator_user_login", null) != null:
			result.moderator_user_login = d["moderator_user_login"]
		if d.get("moderator_user_name", null) != null:
			result.moderator_user_name = d["moderator_user_name"]
		if d.get("action", null) != null:
			result.action = d["action"]
		if d.get("followers", null) != null:
			result.followers = Followers.from_json(d["followers"])
		if d.get("slow", null) != null:
			result.slow = Slow.from_json(d["slow"])
		if d.get("vip", null) != null:
			result.vip = Vip.from_json(d["vip"])
		if d.get("unvip", null) != null:
			result.unvip = Unvip.from_json(d["unvip"])
		if d.get("mod", null) != null:
			result.mod = Mod.from_json(d["mod"])
		if d.get("unmod", null) != null:
			result.unmod = Unmod.from_json(d["unmod"])
		if d.get("ban", null) != null:
			result.ban = Ban.from_json(d["ban"])
		if d.get("unban", null) != null:
			result.unban = Unban.from_json(d["unban"])
		if d.get("timeout", null) != null:
			result.timeout = Timeout.from_json(d["timeout"])
		if d.get("untimeout", null) != null:
			result.untimeout = Untimeout.from_json(d["untimeout"])
		if d.get("raid", null) != null:
			result.raid = Raid.from_json(d["raid"])
		if d.get("unraid", null) != null:
			result.unraid = Unraid.from_json(d["unraid"])
		if d.get("delete", null) != null:
			result.delete = Delete.from_json(d["delete"])
		if d.get("automod_terms", null) != null:
			result.automod_terms = AutomodTerms.from_json(d["automod_terms"])
		if d.get("unban_request", null) != null:
			result.unban_request = UnbanRequest.from_json(d["unban_request"])
		if d.get("shared_chat_ban", null) != null:
			result.shared_chat_ban = d["shared_chat_ban"]
		if d.get("shared_chat_unban", null) != null:
			result.shared_chat_unban = d["shared_chat_unban"]
		if d.get("shared_chat_timeout", null) != null:
			result.shared_chat_timeout = d["shared_chat_timeout"]
		if d.get("shared_chat_untimeout", null) != null:
			result.shared_chat_untimeout = d["shared_chat_untimeout"]
		if d.get("shared_chat_delete", null) != null:
			result.shared_chat_delete = d["shared_chat_delete"]
		return result
	


## Optional.. Metadata associated with the followers command.
## #/components/schemas/ChannelModerateEvent/Followers
class Followers extends TwitchData:

	## The length of time, in minutes, that the followers must have followed the broadcaster to participate in the chat room.
	@export var follow_duration_minutes: int:
		set(val): 
			follow_duration_minutes = val
			track_data(&"follow_duration_minutes", val)
	
	
	
	static func from_json(d: Dictionary) -> Followers:
		var result: Followers = Followers.new()
		if d.get("follow_duration_minutes", null) != null:
			result.follow_duration_minutes = d["follow_duration_minutes"]
		return result
	


## Optional. Metadata associated with the slow command.
## #/components/schemas/ChannelModerateEvent/Slow
class Slow extends TwitchData:

	## The amount of time, in seconds, that users need to wait between sending messages.
	@export var wait_time_seconds: int:
		set(val): 
			wait_time_seconds = val
			track_data(&"wait_time_seconds", val)
	
	
	
	static func from_json(d: Dictionary) -> Slow:
		var result: Slow = Slow.new()
		if d.get("wait_time_seconds", null) != null:
			result.wait_time_seconds = d["wait_time_seconds"]
		return result
	


## Optional. Metadata associated with the vip command.
## #/components/schemas/ChannelModerateEvent/Vip
class Vip extends TwitchData:

	## The ID of the user gaining VIP status.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user gaining VIP status.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user gaining VIP status.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> Vip:
		var result: Vip = Vip.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the unvip command.
## #/components/schemas/ChannelModerateEvent/Unvip
class Unvip extends TwitchData:

	## The ID of the user losing VIP status.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user losing VIP status.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user losing VIP status.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> Unvip:
		var result: Unvip = Unvip.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the mod command.
## #/components/schemas/ChannelModerateEvent/Mod
class Mod extends TwitchData:

	## The ID of the user gaining mod status.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user gaining mod status.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user gaining mod status.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> Mod:
		var result: Mod = Mod.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the unmod command.
## #/components/schemas/ChannelModerateEvent/Unmod
class Unmod extends TwitchData:

	## The ID of the user losing mod status.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user losing mod status.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user losing mod status.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> Unmod:
		var result: Unmod = Unmod.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the ban command.
## #/components/schemas/ChannelModerateEvent/Ban
class Ban extends TwitchData:

	## The ID of the user being banned.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user being banned.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user being banned.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## Optional. Reason given for the ban.
	@export var reason: String:
		set(val): 
			reason = val
			track_data(&"reason", val)
	
	
	
	static func from_json(d: Dictionary) -> Ban:
		var result: Ban = Ban.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("reason", null) != null:
			result.reason = d["reason"]
		return result
	


## Optional. Metadata associated with the unban command.
## #/components/schemas/ChannelModerateEvent/Unban
class Unban extends TwitchData:

	## The ID of the user being unbanned.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user being unbanned.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user being unbanned.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> Unban:
		var result: Unban = Unban.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional.. Metadata associated with the timeout command.
## #/components/schemas/ChannelModerateEvent/Timeout
class Timeout extends TwitchData:

	## The ID of the user being timed out.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user being timed out.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user being timed out.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## Optional.. The reason given for the timeout.
	@export var reason: String:
		set(val): 
			reason = val
			track_data(&"reason", val)
	
	## The time at which the timeout ends.
	@export var expires_at: String:
		set(val): 
			expires_at = val
			track_data(&"expires_at", val)
	
	
	
	static func from_json(d: Dictionary) -> Timeout:
		var result: Timeout = Timeout.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("reason", null) != null:
			result.reason = d["reason"]
		if d.get("expires_at", null) != null:
			result.expires_at = d["expires_at"]
		return result
	


## Optional. Metadata associated with the untimeout command.
## #/components/schemas/ChannelModerateEvent/Untimeout
class Untimeout extends TwitchData:

	## The ID of the user being untimed out.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user being untimed out.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user untimed out.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> Untimeout:
		var result: Untimeout = Untimeout.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional.. Metadata associated with the raid command.
## #/components/schemas/ChannelModerateEvent/Raid
class Raid extends TwitchData:

	## The ID of the user being raided.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user being raided.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user raided.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The viewer count.
	@export var viewer_count: int:
		set(val): 
			viewer_count = val
			track_data(&"viewer_count", val)
	
	
	
	static func from_json(d: Dictionary) -> Raid:
		var result: Raid = Raid.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("viewer_count", null) != null:
			result.viewer_count = d["viewer_count"]
		return result
	


## Optional. Metadata associated with the unraid command.
## #/components/schemas/ChannelModerateEvent/Unraid
class Unraid extends TwitchData:

	## The ID of the user no longer being raided.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user no longer being raided.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the no longer user raided.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> Unraid:
		var result: Unraid = Unraid.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the delete command.
## #/components/schemas/ChannelModerateEvent/Delete
class Delete extends TwitchData:

	## The ID of the user whose message is being deleted.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The ID of the message being deleted.
	@export var message_id: String:
		set(val): 
			message_id = val
			track_data(&"message_id", val)
	
	## The message body of the message being deleted.
	@export var message_body: String:
		set(val): 
			message_body = val
			track_data(&"message_body", val)
	
	
	
	static func from_json(d: Dictionary) -> Delete:
		var result: Delete = Delete.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("message_id", null) != null:
			result.message_id = d["message_id"]
		if d.get("message_body", null) != null:
			result.message_body = d["message_body"]
		return result
	


## Optional. Metadata associated with the automod terms changes.
## #/components/schemas/ChannelModerateEvent/AutomodTerms
class AutomodTerms extends TwitchData:

	## Either “add” or “remove”.
	@export var action: String:
		set(val): 
			action = val
			track_data(&"action", val)
	
	## Either “blocked” or “permitted”.
	@export var list: String:
		set(val): 
			list = val
			track_data(&"list", val)
	
	## Terms being added or removed.
	@export var terms: Array[String]:
		set(val): 
			terms = val
			track_data(&"terms", val)
	
	## Whether the terms were added due to an Automod message approve/deny action.
	@export var from_automod: bool:
		set(val): 
			from_automod = val
			track_data(&"from_automod", val)
	
	
	
	static func from_json(d: Dictionary) -> AutomodTerms:
		var result: AutomodTerms = AutomodTerms.new()
		if d.get("action", null) != null:
			result.action = d["action"]
		if d.get("list", null) != null:
			result.list = d["list"]
		if d.get("terms", null) != null:
			for value in d["terms"]:
				result.terms.append(value)
		if d.get("from_automod", null) != null:
			result.from_automod = d["from_automod"]
		return result
	


## Optional. Metadata associated with an unban request.
## #/components/schemas/ChannelModerateEvent/UnbanRequest
class UnbanRequest extends TwitchData:

	## Whether or not the unban request was approved or denied.
	@export var is_approved: bool:
		set(val): 
			is_approved = val
			track_data(&"is_approved", val)
	
	## The ID of the banned user.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The message included by the moderator explaining their approval or denial.
	@export var moderator_message: String:
		set(val): 
			moderator_message = val
			track_data(&"moderator_message", val)
	
	
	
	static func from_json(d: Dictionary) -> UnbanRequest:
		var result: UnbanRequest = UnbanRequest.new()
		if d.get("is_approved", null) != null:
			result.is_approved = d["is_approved"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("moderator_message", null) != null:
			result.moderator_message = d["moderator_message"]
		return result
	


## 
## #/components/schemas/ChannelModerateEventV2
class EventV2 extends TwitchData:

	## The ID of the broadcaster.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The login of the broadcaster.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The user name of the broadcaster.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The channel in which the action originally occurred. Is the same as the broadcaster_user_id if not in shared chat.
	@export var source_broadcaster_user_id: String:
		set(val): 
			source_broadcaster_user_id = val
			track_data(&"source_broadcaster_user_id", val)
	
	## The channel in which the action originally occurred. Is the same as the broadcaster_user_login if not in shared chat.
	@export var source_broadcaster_user_login: String:
		set(val): 
			source_broadcaster_user_login = val
			track_data(&"source_broadcaster_user_login", val)
	
	## The channel in which the action originally occurred. Is null when the moderator action happens in the same channel as the broadcaster. Is not null when in a shared chat session, and the action happens in the channel of a participant other than the broadcaster.
	@export var source_broadcaster_user_name: String:
		set(val): 
			source_broadcaster_user_name = val
			track_data(&"source_broadcaster_user_name", val)
	
	## The ID of the moderator who performed the action.
	@export var moderator_user_id: String:
		set(val): 
			moderator_user_id = val
			track_data(&"moderator_user_id", val)
	
	## The login of the moderator.
	@export var moderator_user_login: String:
		set(val): 
			moderator_user_login = val
			track_data(&"moderator_user_login", val)
	
	## The user name of the moderator.
	@export var moderator_user_name: String:
		set(val): 
			moderator_user_name = val
			track_data(&"moderator_user_name", val)
	
	## The action performed. Possible values are: bantimeoutunbanuntimeoutclearemoteonlyemoteonlyofffollowersfollowersoffuniquechatuniquechatoffslowslowoffsubscriberssubscribersoffunraiddeleteunvipvipraidadd_blocked_termadd_permitted_termremove_blocked_termremove_permitted_termmodunmodapprove_unban_requestdeny_unban_requestwarnshared_chat_banshared_chat_timeoutshared_chat_unbanshared_chat_untimeoutshared_chat_delete
	@export var action: String:
		set(val): 
			action = val
			track_data(&"action", val)
	
	## Optional. Metadata associated with the followers command.
	@export var followers: FollowersV2:
		set(val): 
			followers = val
			track_data(&"followers", val)
	
	## Optional. Metadata associated with the slow command.
	@export var slow: SlowV2:
		set(val): 
			slow = val
			track_data(&"slow", val)
	
	## Optional. Metadata associated with the vip command.
	@export var vip: VipV2:
		set(val): 
			vip = val
			track_data(&"vip", val)
	
	## Optional. Metadata associated with the unvip command.
	@export var unvip: UnvipV2:
		set(val): 
			unvip = val
			track_data(&"unvip", val)
	
	## Optional. Metadata associated with the mod command.
	@export var mod: ModV2:
		set(val): 
			mod = val
			track_data(&"mod", val)
	
	## Optional. Metadata associated with the unmod command.
	@export var unmod: UnmodV2:
		set(val): 
			unmod = val
			track_data(&"unmod", val)
	
	## Optional. Metadata associated with the ban command.
	@export var ban: BanV2:
		set(val): 
			ban = val
			track_data(&"ban", val)
	
	## Optional. Metadata associated with the unban command.
	@export var unban: UnbanV2:
		set(val): 
			unban = val
			track_data(&"unban", val)
	
	## Optional. Metadata associated with the timeout command.
	@export var timeout: TimeoutV2:
		set(val): 
			timeout = val
			track_data(&"timeout", val)
	
	## Optional. Metadata associated with the untimeout command.
	@export var untimeout: UntimeoutV2:
		set(val): 
			untimeout = val
			track_data(&"untimeout", val)
	
	## Optional. Metadata associated with the raid command.
	@export var raid: RaidV2:
		set(val): 
			raid = val
			track_data(&"raid", val)
	
	## Optional. Metadata associated with the unraid command.
	@export var unraid: UnraidV2:
		set(val): 
			unraid = val
			track_data(&"unraid", val)
	
	## Optional. Metadata associated with the delete command.
	@export var delete: DeleteV2:
		set(val): 
			delete = val
			track_data(&"delete", val)
	
	## Optional. Metadata associated with the automod terms changes.
	@export var automod_terms: AutomodTermsV2:
		set(val): 
			automod_terms = val
			track_data(&"automod_terms", val)
	
	## Optional. Metadata associated with an unban request.
	@export var unban_request: UnbanRequestV2:
		set(val): 
			unban_request = val
			track_data(&"unban_request", val)
	
	## Optional. Metadata associated with the warn command.
	@export var warn: WarnV2:
		set(val): 
			warn = val
			track_data(&"warn", val)
	
	## Optional. Information about the shared_chat_ban event. Is null if action is not shared_chat_ban. This field has the same information as the ban field but for a action that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_ban: Dictionary:
		set(val): 
			shared_chat_ban = val
			track_data(&"shared_chat_ban", val)
	
	## Optional. Information about the shared_chat_unban event. Is null if action is not shared_chat_unban. This field has the same information as the unban field but for a action that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_unban: Dictionary:
		set(val): 
			shared_chat_unban = val
			track_data(&"shared_chat_unban", val)
	
	## Optional. Information about the shared_chat_timeout event. Is null if action is not shared_chat_timeout. This field has the same information as the timeout field but for a action that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_timeout: Dictionary:
		set(val): 
			shared_chat_timeout = val
			track_data(&"shared_chat_timeout", val)
	
	## Optional. Information about the shared_chat_untimeout event. Is null if action is not shared_chat_untimeout. This field has the same information as the untimeout field but for a action that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_untimeout: Dictionary:
		set(val): 
			shared_chat_untimeout = val
			track_data(&"shared_chat_untimeout", val)
	
	## Optional. Information about the shared_chat_delete event. Is null if action is not shared_chat_delete. This field has the same information as the delete field but for a action that happened for a channel in a shared chat session other than the broadcaster in the subscription condition.
	@export var shared_chat_delete: Dictionary:
		set(val): 
			shared_chat_delete = val
			track_data(&"shared_chat_delete", val)
	
	
	
	static func from_json(d: Dictionary) -> EventV2:
		var result: EventV2 = EventV2.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("source_broadcaster_user_id", null) != null:
			result.source_broadcaster_user_id = d["source_broadcaster_user_id"]
		if d.get("source_broadcaster_user_login", null) != null:
			result.source_broadcaster_user_login = d["source_broadcaster_user_login"]
		if d.get("source_broadcaster_user_name", null) != null:
			result.source_broadcaster_user_name = d["source_broadcaster_user_name"]
		if d.get("moderator_user_id", null) != null:
			result.moderator_user_id = d["moderator_user_id"]
		if d.get("moderator_user_login", null) != null:
			result.moderator_user_login = d["moderator_user_login"]
		if d.get("moderator_user_name", null) != null:
			result.moderator_user_name = d["moderator_user_name"]
		if d.get("action", null) != null:
			result.action = d["action"]
		if d.get("followers", null) != null:
			result.followers = FollowersV2.from_json(d["followers"])
		if d.get("slow", null) != null:
			result.slow = SlowV2.from_json(d["slow"])
		if d.get("vip", null) != null:
			result.vip = VipV2.from_json(d["vip"])
		if d.get("unvip", null) != null:
			result.unvip = UnvipV2.from_json(d["unvip"])
		if d.get("mod", null) != null:
			result.mod = ModV2.from_json(d["mod"])
		if d.get("unmod", null) != null:
			result.unmod = UnmodV2.from_json(d["unmod"])
		if d.get("ban", null) != null:
			result.ban = BanV2.from_json(d["ban"])
		if d.get("unban", null) != null:
			result.unban = UnbanV2.from_json(d["unban"])
		if d.get("timeout", null) != null:
			result.timeout = TimeoutV2.from_json(d["timeout"])
		if d.get("untimeout", null) != null:
			result.untimeout = UntimeoutV2.from_json(d["untimeout"])
		if d.get("raid", null) != null:
			result.raid = RaidV2.from_json(d["raid"])
		if d.get("unraid", null) != null:
			result.unraid = UnraidV2.from_json(d["unraid"])
		if d.get("delete", null) != null:
			result.delete = DeleteV2.from_json(d["delete"])
		if d.get("automod_terms", null) != null:
			result.automod_terms = AutomodTermsV2.from_json(d["automod_terms"])
		if d.get("unban_request", null) != null:
			result.unban_request = UnbanRequestV2.from_json(d["unban_request"])
		if d.get("warn", null) != null:
			result.warn = WarnV2.from_json(d["warn"])
		if d.get("shared_chat_ban", null) != null:
			result.shared_chat_ban = d["shared_chat_ban"]
		if d.get("shared_chat_unban", null) != null:
			result.shared_chat_unban = d["shared_chat_unban"]
		if d.get("shared_chat_timeout", null) != null:
			result.shared_chat_timeout = d["shared_chat_timeout"]
		if d.get("shared_chat_untimeout", null) != null:
			result.shared_chat_untimeout = d["shared_chat_untimeout"]
		if d.get("shared_chat_delete", null) != null:
			result.shared_chat_delete = d["shared_chat_delete"]
		return result
	


## Optional. Metadata associated with the followers command.
## #/components/schemas/ChannelModerateEventV2/Followers
class FollowersV2 extends TwitchData:

	## The length of time, in minutes, that the followers must have followed the broadcaster to participate in the chat room.
	@export var follow_duration_minutes: int:
		set(val): 
			follow_duration_minutes = val
			track_data(&"follow_duration_minutes", val)
	
	
	
	static func from_json(d: Dictionary) -> FollowersV2:
		var result: FollowersV2 = FollowersV2.new()
		if d.get("follow_duration_minutes", null) != null:
			result.follow_duration_minutes = d["follow_duration_minutes"]
		return result
	


## Optional. Metadata associated with the slow command.
## #/components/schemas/ChannelModerateEventV2/Slow
class SlowV2 extends TwitchData:

	## The amount of time, in seconds, that users need to wait between sending messages.
	@export var wait_time_seconds: int:
		set(val): 
			wait_time_seconds = val
			track_data(&"wait_time_seconds", val)
	
	
	
	static func from_json(d: Dictionary) -> SlowV2:
		var result: SlowV2 = SlowV2.new()
		if d.get("wait_time_seconds", null) != null:
			result.wait_time_seconds = d["wait_time_seconds"]
		return result
	


## Optional. Metadata associated with the vip command.
## #/components/schemas/ChannelModerateEventV2/Vip
class VipV2 extends TwitchData:

	## The ID of the user gaining VIP status.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user gaining VIP status.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user gaining VIP status.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> VipV2:
		var result: VipV2 = VipV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the unvip command.
## #/components/schemas/ChannelModerateEventV2/Unvip
class UnvipV2 extends TwitchData:

	## The ID of the user losing VIP status.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user losing VIP status.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user losing VIP status.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> UnvipV2:
		var result: UnvipV2 = UnvipV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the mod command.
## #/components/schemas/ChannelModerateEventV2/Mod
class ModV2 extends TwitchData:

	## The ID of the user gaining mod status.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user gaining mod status.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user gaining mod status.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> ModV2:
		var result: ModV2 = ModV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the unmod command.
## #/components/schemas/ChannelModerateEventV2/Unmod
class UnmodV2 extends TwitchData:

	## The ID of the user losing mod status.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user losing mod status.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user losing mod status.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> UnmodV2:
		var result: UnmodV2 = UnmodV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the ban command.
## #/components/schemas/ChannelModerateEventV2/Ban
class BanV2 extends TwitchData:

	## The ID of the user being banned.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user being banned.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user being banned.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## Optional. Reason given for the ban.
	@export var reason: String:
		set(val): 
			reason = val
			track_data(&"reason", val)
	
	
	
	static func from_json(d: Dictionary) -> BanV2:
		var result: BanV2 = BanV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("reason", null) != null:
			result.reason = d["reason"]
		return result
	


## Optional. Metadata associated with the unban command.
## #/components/schemas/ChannelModerateEventV2/Unban
class UnbanV2 extends TwitchData:

	## The ID of the user being unbanned.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user being unbanned.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user being unbanned.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> UnbanV2:
		var result: UnbanV2 = UnbanV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the timeout command.
## #/components/schemas/ChannelModerateEventV2/Timeout
class TimeoutV2 extends TwitchData:

	## The ID of the user being timed out.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user being timed out.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user being timed out.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## Optional. The reason given for the timeout.
	@export var reason: String:
		set(val): 
			reason = val
			track_data(&"reason", val)
	
	## The time at which the timeout ends.
	@export var expires_at: String:
		set(val): 
			expires_at = val
			track_data(&"expires_at", val)
	
	
	
	static func from_json(d: Dictionary) -> TimeoutV2:
		var result: TimeoutV2 = TimeoutV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("reason", null) != null:
			result.reason = d["reason"]
		if d.get("expires_at", null) != null:
			result.expires_at = d["expires_at"]
		return result
	


## Optional. Metadata associated with the untimeout command.
## #/components/schemas/ChannelModerateEventV2/Untimeout
class UntimeoutV2 extends TwitchData:

	## The ID of the user being untimed out.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user being untimed out.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user untimed out.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> UntimeoutV2:
		var result: UntimeoutV2 = UntimeoutV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the raid command.
## #/components/schemas/ChannelModerateEventV2/Raid
class RaidV2 extends TwitchData:

	## The ID of the user being raided.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user being raided.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user raided.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The viewer count.
	@export var viewer_count: int:
		set(val): 
			viewer_count = val
			track_data(&"viewer_count", val)
	
	
	
	static func from_json(d: Dictionary) -> RaidV2:
		var result: RaidV2 = RaidV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("viewer_count", null) != null:
			result.viewer_count = d["viewer_count"]
		return result
	


## Optional. Metadata associated with the unraid command.
## #/components/schemas/ChannelModerateEventV2/Unraid
class UnraidV2 extends TwitchData:

	## The ID of the user no longer being raided.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user no longer being raided.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the no longer user raided.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> UnraidV2:
		var result: UnraidV2 = UnraidV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		return result
	


## Optional. Metadata associated with the delete command.
## #/components/schemas/ChannelModerateEventV2/Delete
class DeleteV2 extends TwitchData:

	## The ID of the user whose message is being deleted.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The ID of the message being deleted.
	@export var message_id: String:
		set(val): 
			message_id = val
			track_data(&"message_id", val)
	
	## The message body of the message being deleted.
	@export var message_body: String:
		set(val): 
			message_body = val
			track_data(&"message_body", val)
	
	
	
	static func from_json(d: Dictionary) -> DeleteV2:
		var result: DeleteV2 = DeleteV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("message_id", null) != null:
			result.message_id = d["message_id"]
		if d.get("message_body", null) != null:
			result.message_body = d["message_body"]
		return result
	


## Optional. Metadata associated with the automod terms changes.
## #/components/schemas/ChannelModerateEventV2/AutomodTerms
class AutomodTermsV2 extends TwitchData:

	## Either “add” or “remove”.
	@export var action: String:
		set(val): 
			action = val
			track_data(&"action", val)
	
	## Either “blocked” or “permitted”.
	@export var list: String:
		set(val): 
			list = val
			track_data(&"list", val)
	
	## Terms being added or removed.
	@export var terms: Array[String]:
		set(val): 
			terms = val
			track_data(&"terms", val)
	
	## Whether the terms were added due to an Automod message approve/deny action.
	@export var from_automod: bool:
		set(val): 
			from_automod = val
			track_data(&"from_automod", val)
	
	
	
	static func from_json(d: Dictionary) -> AutomodTermsV2:
		var result: AutomodTermsV2 = AutomodTermsV2.new()
		if d.get("action", null) != null:
			result.action = d["action"]
		if d.get("list", null) != null:
			result.list = d["list"]
		if d.get("terms", null) != null:
			for value in d["terms"]:
				result.terms.append(value)
		if d.get("from_automod", null) != null:
			result.from_automod = d["from_automod"]
		return result
	


## Optional. Metadata associated with an unban request.
## #/components/schemas/ChannelModerateEventV2/UnbanRequest
class UnbanRequestV2 extends TwitchData:

	## Whether or not the unban request was approved or denied.
	@export var is_approved: bool:
		set(val): 
			is_approved = val
			track_data(&"is_approved", val)
	
	## The ID of the banned user.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The message included by the moderator explaining their approval or denial.
	@export var moderator_message: String:
		set(val): 
			moderator_message = val
			track_data(&"moderator_message", val)
	
	
	
	static func from_json(d: Dictionary) -> UnbanRequestV2:
		var result: UnbanRequestV2 = UnbanRequestV2.new()
		if d.get("is_approved", null) != null:
			result.is_approved = d["is_approved"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("moderator_message", null) != null:
			result.moderator_message = d["moderator_message"]
		return result
	


## Optional. Metadata associated with the warn command.
## #/components/schemas/ChannelModerateEventV2/Warn
class WarnV2 extends TwitchData:

	## The ID of the user being warned.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The login of the user being warned.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user name of the user being warned.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## Optional. Reason given for the warning.
	@export var reason: String:
		set(val): 
			reason = val
			track_data(&"reason", val)
	
	## Optional. Chat rules cited for the warning.
	@export var chat_rules_cited: Array[String]:
		set(val): 
			chat_rules_cited = val
			track_data(&"chat_rules_cited", val)
	
	
	
	static func from_json(d: Dictionary) -> WarnV2:
		var result: WarnV2 = WarnV2.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("reason", null) != null:
			result.reason = d["reason"]
		if d.get("chat_rules_cited", null) != null:
			for value in d["chat_rules_cited"]:
				result.chat_rules_cited.append(value)
		return result
	