@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/TopContributions
class_name TwitchESTopContributions
	
## The ID of the user that made the contribution.
@export var user_id: String:
	set(val): 
		user_id = val
		track_data(&"user_id", val)

## The user’s login name.
@export var user_login: String:
	set(val): 
		user_login = val
		track_data(&"user_login", val)

## The user’s display name.
@export var user_name: String:
	set(val): 
		user_name = val
		track_data(&"user_name", val)

## The contribution method used. Possible values are: bits — Cheering with Bits.subscription — Subscription activity like subscribing or gifting subscriptions.other — Covers other contribution methods not listed.
@export var type: String:
	set(val): 
		type = val
		track_data(&"type", val)

## The total amount contributed. If type is bits, total represents the amount of Bits used. If type is subscription, total is 500, 1000, or 2500 to represent tier 1, 2, or 3 subscriptions, respectively.
@export var total: int:
	set(val): 
		total = val
		track_data(&"total", val)



static func from_json(d: Dictionary) -> TwitchESTopContributions:
	var result: TwitchESTopContributions = TwitchESTopContributions.new()
	if d.get("user_id", null) != null:
		result.user_id = d["user_id"]
	if d.get("user_login", null) != null:
		result.user_login = d["user_login"]
	if d.get("user_name", null) != null:
		result.user_name = d["user_name"]
	if d.get("type", null) != null:
		result.type = d["type"]
	if d.get("total", null) != null:
		result.total = d["total"]
	return result
