@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelChatMessageDelete
	


## 
## #/components/schemas/ChannelChatMessageDeleteCondition
class Condition extends TwitchData:

	## User ID of the channel to receive chat message delete events for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The user ID to read chat as.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		return result
	


## 
## #/components/schemas/ChannelChatMessageDeleteEvent
class Event extends TwitchData:

	## The broadcaster user ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The ID of the user whose message was deleted.
	@export var target_user_id: String:
		set(val): 
			target_user_id = val
			track_data(&"target_user_id", val)
	
	## The user name of the user whose message was deleted.
	@export var target_user_name: String:
		set(val): 
			target_user_name = val
			track_data(&"target_user_name", val)
	
	## The user login of the user whose message was deleted.
	@export var target_user_login: String:
		set(val): 
			target_user_login = val
			track_data(&"target_user_login", val)
	
	## A UUID that identifies the message that was removed.
	@export var message_id: String:
		set(val): 
			message_id = val
			track_data(&"message_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("target_user_id", null) != null:
			result.target_user_id = d["target_user_id"]
		if d.get("target_user_name", null) != null:
			result.target_user_name = d["target_user_name"]
		if d.get("target_user_login", null) != null:
			result.target_user_login = d["target_user_login"]
		if d.get("message_id", null) != null:
			result.message_id = d["message_id"]
		return result
	