@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/Image
class_name TwitchESTwitchImage
	
## URL for the image at 1x size.
@export var url_1x: String:
	set(val): 
		url_1x = val
		track_data(&"url_1x", val)

## URL for the image at 2x size.
@export var url_2x: String:
	set(val): 
		url_2x = val
		track_data(&"url_2x", val)

## URL for the image at 4x size.
@export var url_4x: String:
	set(val): 
		url_4x = val
		track_data(&"url_4x", val)



static func from_json(d: Dictionary) -> TwitchESTwitchImage:
	var result: TwitchESTwitchImage = TwitchESTwitchImage.new()
	if d.get("url_1x", null) != null:
		result.url_1x = d["url_1x"]
	if d.get("url_2x", null) != null:
		result.url_2x = d["url_2x"]
	if d.get("url_4x", null) != null:
		result.url_4x = d["url_4x"]
	return result
