@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESCharityCampaignStart
	


## 
## #/components/schemas/CharityCampaignStartEvent
class Event extends TwitchData:

	## An ID that identifies the charity campaign.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## An ID that identifies the broadcaster that’s running the campaign.
	@export var broadcaster_id: String:
		set(val): 
			broadcaster_id = val
			track_data(&"broadcaster_id", val)
	
	## The broadcaster’s login name.
	@export var broadcaster_login: String:
		set(val): 
			broadcaster_login = val
			track_data(&"broadcaster_login", val)
	
	## The broadcaster’s display name.
	@export var broadcaster_name: String:
		set(val): 
			broadcaster_name = val
			track_data(&"broadcaster_name", val)
	
	## The charity’s name.
	@export var charity_name: String:
		set(val): 
			charity_name = val
			track_data(&"charity_name", val)
	
	## A description of the charity.
	@export var charity_description: String:
		set(val): 
			charity_description = val
			track_data(&"charity_description", val)
	
	## A URL to an image of the charity’s logo. The image’s type is PNG and its size is 100px X 100px.
	@export var charity_logo: String:
		set(val): 
			charity_logo = val
			track_data(&"charity_logo", val)
	
	## A URL to the charity’s website.
	@export var charity_website: String:
		set(val): 
			charity_website = val
			track_data(&"charity_website", val)
	
	## An object that contains the current amount of donations that the campaign has received.
	@export var current_amount: CurrentAmount:
		set(val): 
			current_amount = val
			track_data(&"current_amount", val)
	
	## An object that contains the campaign’s target fundraising goal.
	@export var target_amount: TargetAmount:
		set(val): 
			target_amount = val
			track_data(&"target_amount", val)
	
	## The UTC timestamp (in RFC3339 format) of when the broadcaster started the campaign.
	@export var started_at: String:
		set(val): 
			started_at = val
			track_data(&"started_at", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("broadcaster_id", null) != null:
			result.broadcaster_id = d["broadcaster_id"]
		if d.get("broadcaster_login", null) != null:
			result.broadcaster_login = d["broadcaster_login"]
		if d.get("broadcaster_name", null) != null:
			result.broadcaster_name = d["broadcaster_name"]
		if d.get("charity_name", null) != null:
			result.charity_name = d["charity_name"]
		if d.get("charity_description", null) != null:
			result.charity_description = d["charity_description"]
		if d.get("charity_logo", null) != null:
			result.charity_logo = d["charity_logo"]
		if d.get("charity_website", null) != null:
			result.charity_website = d["charity_website"]
		if d.get("current_amount", null) != null:
			result.current_amount = CurrentAmount.from_json(d["current_amount"])
		if d.get("target_amount", null) != null:
			result.target_amount = TargetAmount.from_json(d["target_amount"])
		if d.get("started_at", null) != null:
			result.started_at = d["started_at"]
		return result
	


## An object that contains the current amount of donations that the campaign has received.
## #/components/schemas/CharityCampaignStartEvent/CurrentAmount
class CurrentAmount extends TwitchData:

	## The monetary amount. The amount is specified in the currency’s minor unit. For example, the minor units for USD is cents, so if the amount is $5.50 USD, value is set to 550.
	@export var value: int:
		set(val): 
			value = val
			track_data(&"value", val)
	
	## The number of decimal places used by the currency. For example, USD uses two decimal places. Use this number to translate value from minor units to major units by using the formula:value / 10^decimal_places
	@export var decimal_places: int:
		set(val): 
			decimal_places = val
			track_data(&"decimal_places", val)
	
	## The ISO-4217 three-letter currency code that identifies the type of currency in value.
	@export var currency: String:
		set(val): 
			currency = val
			track_data(&"currency", val)
	
	
	
	static func from_json(d: Dictionary) -> CurrentAmount:
		var result: CurrentAmount = CurrentAmount.new()
		if d.get("value", null) != null:
			result.value = d["value"]
		if d.get("decimal_places", null) != null:
			result.decimal_places = d["decimal_places"]
		if d.get("currency", null) != null:
			result.currency = d["currency"]
		return result
	


## An object that contains the campaign’s target fundraising goal.
## #/components/schemas/CharityCampaignStartEvent/TargetAmount
class TargetAmount extends TwitchData:

	## The monetary amount. The amount is specified in the currency’s minor unit. For example, the minor units for USD is cents, so if the amount is $5.50 USD, value is set to 550.
	@export var value: int:
		set(val): 
			value = val
			track_data(&"value", val)
	
	## The number of decimal places used by the currency. For example, USD uses two decimal places. Use this number to translate value from minor units to major units by using the formula:value / 10^decimal_places
	@export var decimal_places: int:
		set(val): 
			decimal_places = val
			track_data(&"decimal_places", val)
	
	## The ISO-4217 three-letter currency code that identifies the type of currency in value.
	@export var currency: String:
		set(val): 
			currency = val
			track_data(&"currency", val)
	
	
	
	static func from_json(d: Dictionary) -> TargetAmount:
		var result: TargetAmount = TargetAmount.new()
		if d.get("value", null) != null:
			result.value = d["value"]
		if d.get("decimal_places", null) != null:
			result.decimal_places = d["decimal_places"]
		if d.get("currency", null) != null:
			result.currency = d["currency"]
		return result
	