@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/GlobalCooldown
class_name TwitchESGlobalCooldown
	
## Is the setting enabled.
@export var is_enabled: bool:
	set(val): 
		is_enabled = val
		track_data(&"is_enabled", val)

## The cooldown in seconds.
@export var seconds: int:
	set(val): 
		seconds = val
		track_data(&"seconds", val)



static func from_json(d: Dictionary) -> TwitchESGlobalCooldown:
	var result: TwitchESGlobalCooldown = TwitchESGlobalCooldown.new()
	if d.get("is_enabled", null) != null:
		result.is_enabled = d["is_enabled"]
	if d.get("seconds", null) != null:
		result.seconds = d["seconds"]
	return result
