@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/CustomPowerUp
class_name TwitchESCustomPowerUp
	
## The unique ID for this Custom Power-up.
@export var id: String:
	set(val):
		id = val
		track_data(&"id", val)

## The user-viewable name of this Custom Power-up.
@export var title: String:
	set(val):
		title = val
		track_data(&"title", val)

## The cost of the Custom Power-up to redeem.
@export var bits_cost: int:
	set(val):
		bits_cost = val
		track_data(&"bits_cost", val)

## The creator-provided description for this Power-up.
@export var prompt: String:
	set(val):
		prompt = val
		track_data(&"prompt", val)



## Constructor with all required fields.
static func create() -> TwitchESCustomPowerUp:
	var twitch_es_custom_power_up: TwitchESCustomPowerUp = TwitchESCustomPowerUp.new()
	return twitch_es_custom_power_up


static func from_json(d: Dictionary) -> TwitchESCustomPowerUp:
	var result: TwitchESCustomPowerUp = TwitchESCustomPowerUp.new()
	if d.get("id", null) != null:
		result.id = d["id"]
	if d.get("title", null) != null:
		result.title = d["title"]
	if d.get("bits_cost", null) != null:
		result.bits_cost = d["bits_cost"]
	if d.get("prompt", null) != null:
		result.prompt = d["prompt"]
	return result

