@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/Emotes
class_name TwitchESEmotes
	
## The index of where the Emote starts in the text.
@export var begin: int:
	set(val): 
		begin = val
		track_data(&"begin", val)

## The index of where the Emote ends in the text.
@export var end: int:
	set(val): 
		end = val
		track_data(&"end", val)

## The emote ID.
@export var id: String:
	set(val): 
		id = val
		track_data(&"id", val)



static func from_json(d: Dictionary) -> TwitchESEmotes:
	var result: TwitchESEmotes = TwitchESEmotes.new()
	if d.get("begin", null) != null:
		result.begin = d["begin"]
	if d.get("end", null) != null:
		result.end = d["end"]
	if d.get("id", null) != null:
		result.id = d["id"]
	return result
