@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESUserUpdate
	


## 
## #/components/schemas/UserUpdateCondition
class Condition extends TwitchData:

	## The user ID for the user you want update notifications for.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		return result
	


## 
## #/components/schemas/UserUpdateEvent
class Event extends TwitchData:

	## The user’s user id.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The user’s user login.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user’s user display name.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The user’s email address. The event includes the user’s email address only if the app used to request this event type includes the user:read:email scope for the user; otherwise, the field is set to an empty string. See Create EventSub Subscription.
	@export var email: String:
		set(val): 
			email = val
			track_data(&"email", val)
	
	## A Boolean value that determines whether Twitch has verified the user’s email address. Is true if Twitch has verified the email address; otherwise, false.NOTE: Ignore this field if the email field contains an empty string.
	@export var email_verified: bool:
		set(val): 
			email_verified = val
			track_data(&"email_verified", val)
	
	## The user’s description.
	@export var description: String:
		set(val): 
			description = val
			track_data(&"description", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("email", null) != null:
			result.email = d["email"]
		if d.get("email_verified", null) != null:
			result.email_verified = d["email_verified"]
		if d.get("description", null) != null:
			result.description = d["description"]
		return result
	