@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelUnbanRequestResolve
	


## 
## #/components/schemas/ChannelUnbanRequestResolveCondition
class Condition extends TwitchData:

	## The ID of the user that has permission to moderate the broadcaster’s channel and has granted your app permission to subscribe to this subscription type.
	@export var moderator_user_id: String:
		set(val): 
			moderator_user_id = val
			track_data(&"moderator_user_id", val)
	
	## The ID of the broadcaster you want to get unban request resolution notifications for. Maximum: 1.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("moderator_user_id", null) != null:
			result.moderator_user_id = d["moderator_user_id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelUnbanRequestResolveEvent
class Event extends TwitchData:

	## The ID of the unban request.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## The broadcaster’s user ID for the channel the unban request was updated for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The broadcaster’s login name.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The broadcaster’s display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## Optional. User ID of moderator who approved/denied the request.
	@export var moderator_id: String:
		set(val): 
			moderator_id = val
			track_data(&"moderator_id", val)
	
	## Optional. The moderator’s login name
	@export var moderator_login: String:
		set(val): 
			moderator_login = val
			track_data(&"moderator_login", val)
	
	## Optional. The moderator’s display name
	@export var moderator_name: String:
		set(val): 
			moderator_name = val
			track_data(&"moderator_name", val)
	
	## User ID of user that requested to be unbanned.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The user’s login name.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user’s display name.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## Optional. Resolution text supplied by the mod/broadcaster upon approval/denial of the request.
	@export var resolution_text: String:
		set(val): 
			resolution_text = val
			track_data(&"resolution_text", val)
	
	## Dictates whether the unban request was approved or denied. Can be the following: approvedcanceleddenied
	@export var status: String:
		set(val): 
			status = val
			track_data(&"status", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("moderator_id", null) != null:
			result.moderator_id = d["moderator_id"]
		if d.get("moderator_login", null) != null:
			result.moderator_login = d["moderator_login"]
		if d.get("moderator_name", null) != null:
			result.moderator_name = d["moderator_name"]
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("resolution_text", null) != null:
			result.resolution_text = d["resolution_text"]
		if d.get("status", null) != null:
			result.status = d["status"]
		return result
	