@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESDropEntitlementGrant
	


## 
## #/components/schemas/DropEntitlementGrantCondition
class Condition extends TwitchData:

	## The organization ID of the organization that owns the game on the developer portal.
	@export var organization_id: String:
		set(val): 
			organization_id = val
			track_data(&"organization_id", val)
	
	## The category (or game) ID of the game for which entitlement notifications will be received.
	@export var category_id: String:
		set(val): 
			category_id = val
			track_data(&"category_id", val)
	
	## The campaign ID for a specific campaign for which entitlement notifications will be received.
	@export var campaign_id: String:
		set(val): 
			campaign_id = val
			track_data(&"campaign_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("organization_id", null) != null:
			result.organization_id = d["organization_id"]
		if d.get("category_id", null) != null:
			result.category_id = d["category_id"]
		if d.get("campaign_id", null) != null:
			result.campaign_id = d["campaign_id"]
		return result
	


## 
## #/components/schemas/DropEntitlementGrantEvent
class Event extends TwitchData:

	## Individual event ID, as assigned by EventSub. Use this for de-duplicating messages.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## Entitlement object.
	@export var data: Array[Variant]:
		set(val): 
			data = val
			track_data(&"data", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("data", null) != null:
			for value in d["data"]:
				result.data.append(value)
		return result
	