@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESHypeTrainEnd
	


## 
## #/components/schemas/HypeTrainEndCondition
class Condition extends TwitchData:

	## The ID of the broadcaster that you want to get Hype Train end notifications for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/HypeTrainEndEvent
class Event extends TwitchData:

	## The Hype Train ID.
	@export var id: String:
		set(val): 
			id = val
			track_data(&"id", val)
	
	## The requested broadcaster ID.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The requested broadcaster login.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The requested broadcaster display name.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## Total points contributed to the Hype Train.
	@export var total: int:
		set(val): 
			total = val
			track_data(&"total", val)
	
	## The contributors with the most points contributed.
	@export var top_contributions: Array[TopContributions]:
		set(val): 
			top_contributions = val
			track_data(&"top_contributions", val)
	
	## The current level of the Hype Train.
	@export var level: int:
		set(val): 
			level = val
			track_data(&"level", val)
	
	## Optional. Non-null for a shared Hype Train. Contains the list of broadcasters in the shared Hype Train.
	@export var shared_train_participants: Array[SharedTrainParticipants]:
		set(val): 
			shared_train_participants = val
			track_data(&"shared_train_participants", val)
	
	## The time when the Hype Train started.
	@export var started_at: String:
		set(val): 
			started_at = val
			track_data(&"started_at", val)
	
	## The time when the Hype Train cooldown ends so that the next Hype Train can start.
	@export var cooldown_ends_at: String:
		set(val): 
			cooldown_ends_at = val
			track_data(&"cooldown_ends_at", val)
	
	## The time when the Hype Train ended.
	@export var ended_at: String:
		set(val): 
			ended_at = val
			track_data(&"ended_at", val)
	
	## The type of the Hype Train. Possible values are: treasure golden_kapparegular
	@export var type: String:
		set(val): 
			type = val
			track_data(&"type", val)
	
	## Indicates if the Hype Train is shared. When true, shared_train_participants will contain the list of broadcasters the train is shared with.
	@export var is_shared_train: bool:
		set(val): 
			is_shared_train = val
			track_data(&"is_shared_train", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("id", null) != null:
			result.id = d["id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("total", null) != null:
			result.total = d["total"]
		if d.get("top_contributions", null) != null:
			for value in d["top_contributions"]:
				result.top_contributions.append(TopContributions.from_json(value))
		if d.get("level", null) != null:
			result.level = d["level"]
		if d.get("shared_train_participants", null) != null:
			for value in d["shared_train_participants"]:
				result.shared_train_participants.append(SharedTrainParticipants.from_json(value))
		if d.get("started_at", null) != null:
			result.started_at = d["started_at"]
		if d.get("cooldown_ends_at", null) != null:
			result.cooldown_ends_at = d["cooldown_ends_at"]
		if d.get("ended_at", null) != null:
			result.ended_at = d["ended_at"]
		if d.get("type", null) != null:
			result.type = d["type"]
		if d.get("is_shared_train", null) != null:
			result.is_shared_train = d["is_shared_train"]
		return result
	


## The contributors with the most points contributed.
## #/components/schemas/HypeTrainEndEvent/TopContributions
class TopContributions extends TwitchData:

	## The ID of the user that made the contribution.
	@export var user_id: String:
		set(val): 
			user_id = val
			track_data(&"user_id", val)
	
	## The user’s login name.
	@export var user_login: String:
		set(val): 
			user_login = val
			track_data(&"user_login", val)
	
	## The user’s display name.
	@export var user_name: String:
		set(val): 
			user_name = val
			track_data(&"user_name", val)
	
	## The contribution method used. Possible values are: bits - Bits contributions with Cheering, Power-ups, and Extensions. subscription - Subscription activity like subscribing or gifting subscriptions. other - Covers other contribution methods not listed.
	@export var type: String:
		set(val): 
			type = val
			track_data(&"type", val)
	
	## The total amount contributed. If type is bits, total represents the amount of Bits used. If type is subscription, total is 500, 1000, or 2500 to represent tier 1, 2, or 3 subscriptions, respectively.
	@export var total: int:
		set(val): 
			total = val
			track_data(&"total", val)
	
	
	
	static func from_json(d: Dictionary) -> TopContributions:
		var result: TopContributions = TopContributions.new()
		if d.get("user_id", null) != null:
			result.user_id = d["user_id"]
		if d.get("user_login", null) != null:
			result.user_login = d["user_login"]
		if d.get("user_name", null) != null:
			result.user_name = d["user_name"]
		if d.get("type", null) != null:
			result.type = d["type"]
		if d.get("total", null) != null:
			result.total = d["total"]
		return result
	


## Optional. Non-null for a shared Hype Train. Contains the list of broadcasters in the shared Hype Train.
## #/components/schemas/HypeTrainEndEvent/SharedTrainParticipants
class SharedTrainParticipants extends TwitchData:

	## The ID of the broadcaster participating in the shared Hype Train.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The login of the broadcaster participating in the shared Hype Train.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The display name of the broadcaster participating in the shared Hype Train.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	
	
	static func from_json(d: Dictionary) -> SharedTrainParticipants:
		var result: SharedTrainParticipants = SharedTrainParticipants.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		return result
	