@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

class_name TwitchESChannelSharedChatSessionBegin
	


## 
## #/components/schemas/ChannelSharedChatSessionBeginCondition
class Condition extends TwitchData:

	## The User ID of the channel to receive shared chat session begin events for.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	
	
	static func from_json(d: Dictionary) -> Condition:
		var result: Condition = Condition.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		return result
	


## 
## #/components/schemas/ChannelSharedChatSessionBeginEvent
class Event extends TwitchData:

	## The unique identifier for the shared chat session.
	@export var session_id: String:
		set(val): 
			session_id = val
			track_data(&"session_id", val)
	
	## The User ID of the channel in the subscription condition which is now active in the shared chat session.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The display name of the channel in the subscription condition which is now active in the shared chat session.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The user login of the channel in the subscription condition which is now active in the shared chat session.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	## The User ID of the host channel.
	@export var host_broadcaster_user_id: String:
		set(val): 
			host_broadcaster_user_id = val
			track_data(&"host_broadcaster_user_id", val)
	
	## The display name of the host channel.
	@export var host_broadcaster_user_name: String:
		set(val): 
			host_broadcaster_user_name = val
			track_data(&"host_broadcaster_user_name", val)
	
	## The user login of the host channel.
	@export var host_broadcaster_user_login: String:
		set(val): 
			host_broadcaster_user_login = val
			track_data(&"host_broadcaster_user_login", val)
	
	## The list of participants in the session.
	@export var participants: Array[Participants]:
		set(val): 
			participants = val
			track_data(&"participants", val)
	
	
	
	static func from_json(d: Dictionary) -> Event:
		var result: Event = Event.new()
		if d.get("session_id", null) != null:
			result.session_id = d["session_id"]
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		if d.get("host_broadcaster_user_id", null) != null:
			result.host_broadcaster_user_id = d["host_broadcaster_user_id"]
		if d.get("host_broadcaster_user_name", null) != null:
			result.host_broadcaster_user_name = d["host_broadcaster_user_name"]
		if d.get("host_broadcaster_user_login", null) != null:
			result.host_broadcaster_user_login = d["host_broadcaster_user_login"]
		if d.get("participants", null) != null:
			for value in d["participants"]:
				result.participants.append(Participants.from_json(value))
		return result
	


## The list of participants in the session.
## #/components/schemas/ChannelSharedChatSessionBeginEvent/Participants
class Participants extends TwitchData:

	## The User ID of the participant channel.
	@export var broadcaster_user_id: String:
		set(val): 
			broadcaster_user_id = val
			track_data(&"broadcaster_user_id", val)
	
	## The display name of the participant channel.
	@export var broadcaster_user_name: String:
		set(val): 
			broadcaster_user_name = val
			track_data(&"broadcaster_user_name", val)
	
	## The user login of the participant channel.
	@export var broadcaster_user_login: String:
		set(val): 
			broadcaster_user_login = val
			track_data(&"broadcaster_user_login", val)
	
	
	
	static func from_json(d: Dictionary) -> Participants:
		var result: Participants = Participants.new()
		if d.get("broadcaster_user_id", null) != null:
			result.broadcaster_user_id = d["broadcaster_user_id"]
		if d.get("broadcaster_user_name", null) != null:
			result.broadcaster_user_name = d["broadcaster_user_name"]
		if d.get("broadcaster_user_login", null) != null:
			result.broadcaster_user_login = d["broadcaster_user_login"]
		return result
	