@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/Product
class_name TwitchESProduct
	
## Product name.
@export var name: String:
	set(val): 
		name = val
		track_data(&"name", val)

## Bits involved in the transaction.
@export var bits: int:
	set(val): 
		bits = val
		track_data(&"bits", val)

## Unique identifier for the product acquired.
@export var sku: String:
	set(val): 
		sku = val
		track_data(&"sku", val)

## Flag indicating if the product is in development. If in_development is true, bits will be 0.
@export var in_development: bool:
	set(val): 
		in_development = val
		track_data(&"in_development", val)



static func from_json(d: Dictionary) -> TwitchESProduct:
	var result: TwitchESProduct = TwitchESProduct.new()
	if d.get("name", null) != null:
		result.name = d["name"]
	if d.get("bits", null) != null:
		result.bits = d["bits"]
	if d.get("sku", null) != null:
		result.sku = d["sku"]
	if d.get("in_development", null) != null:
		result.in_development = d["in_development"]
	return result
