@tool
extends TwitchData

# CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

## 
## #/components/schemas/Choices
class_name TwitchESChoices
	
## ID for the choice.
@export var id: String:
	set(val): 
		id = val
		track_data(&"id", val)

## Text displayed for the choice.
@export var title: String:
	set(val): 
		title = val
		track_data(&"title", val)

## Not used; will be set to 0.
@export var bits_votes: int:
	set(val): 
		bits_votes = val
		track_data(&"bits_votes", val)

## Number of votes received via Channel Points.
@export var channel_points_votes: int:
	set(val): 
		channel_points_votes = val
		track_data(&"channel_points_votes", val)

## Total number of votes received for the choice across all methods of voting.
@export var votes: int:
	set(val): 
		votes = val
		track_data(&"votes", val)



static func from_json(d: Dictionary) -> TwitchESChoices:
	var result: TwitchESChoices = TwitchESChoices.new()
	if d.get("id", null) != null:
		result.id = d["id"]
	if d.get("title", null) != null:
		result.title = d["title"]
	if d.get("bits_votes", null) != null:
		result.bits_votes = d["bits_votes"]
	if d.get("channel_points_votes", null) != null:
		result.channel_points_votes = d["channel_points_votes"]
	if d.get("votes", null) != null:
		result.votes = d["votes"]
	return result
